'use client';

import { useEffect, useMemo, useState } from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:8000/api/v1';
type Audit={id:string;actor_user_id:string|null;actor_role:string|null;action:string;entity_type:string;entity_id:string|null;summary:string;created_at:string};
export default function AuditPage(){
 const [token,setToken]=useState('');const [rows,setRows]=useState<Audit[]>([]);const [error,setError]=useState('');const [query,setQuery]=useState('');const [role,setRole]=useState('');const [loading,setLoading]=useState(false);const auth=useMemo(()=>({Authorization:`Bearer ${token}`}),[token]);
 async function load(){setError('');setLoading(true);try{const r=await fetch(`${API}/admin/audit?limit=300`,{headers:auth,cache:'no-store'});let b:any=null;try{b=await r.json()}catch{}if(r.status===401||r.status===403){localStorage.removeItem('sbp_padel_hq_token');location.href='/hq';return}if(!r.ok)throw new Error(b?.detail||'Request failed');setRows(b)}catch(e){setError(e instanceof Error?e.message:'Unable to load audit log')}finally{setLoading(false)}}
 useEffect(()=>{const t=localStorage.getItem('sbp_padel_hq_token')||'';if(!t){location.href='/hq';return}setToken(t)},[]);useEffect(()=>{if(token)load()},[token]);
 const roles=useMemo(()=>[...new Set(rows.map(r=>r.actor_role||'system'))].sort(),[rows]);const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return rows.filter(r=>(!role||(r.actor_role||'system')===role)&&(!q||`${r.action} ${r.entity_type} ${r.summary} ${r.entity_id||''}`.toLowerCase().includes(q)))},[rows,query,role]);
 return <main className="main"><header className="top"><div><h1>Audit Log</h1><p>Administrative and venue-operation changes across SBP Padel.</p></div><div className="toolbar"><button className="btn" disabled={loading} onClick={load}>{loading?'LOADING…':'REFRESH'}</button><a className="btn" href="/hq">BACK TO HQ</a></div></header>{error&&<div className="error">{error}</div>}<section className="card bookingFilters"><input placeholder="Search action, entity or summary" value={query} onChange={e=>setQuery(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}><option value="">All actor roles</option>{roles.map(r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select><span style={{color:'var(--muted)',fontSize:11}}>{filtered.length} of {rows.length} events</span></section><section className="section"><div className="table"><table><thead><tr><th>TIME</th><th>ROLE</th><th>ACTION</th><th>ENTITY</th><th>SUMMARY</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString()}</td><td><span className="status">{(r.actor_role||'system').toUpperCase()}</span></td><td>{r.action}</td><td>{r.entity_type}</td><td>{r.summary}</td></tr>)}{!filtered.length&&!loading&&<tr><td colSpan={5}>No audit events match the current filters.</td></tr>}</tbody></table></div></section></main>
}
