package pk.gov.punjab.sbp.padel;

import android.Manifest; import android.app.Activity; import android.app.AlertDialog; import android.content.Intent; import android.content.pm.PackageManager; import android.graphics.Color; import android.net.Uri; import android.os.Build; import android.os.Bundle; import android.text.InputType; import android.view.View; import android.view.WindowInsets; import android.view.WindowInsetsController; import android.view.WindowManager; import android.webkit.GeolocationPermissions; import android.webkit.JavascriptInterface; import android.webkit.ValueCallback; import android.webkit.WebChromeClient; import android.webkit.WebResourceRequest; import android.webkit.WebSettings; import android.webkit.WebView; import android.webkit.WebViewClient; import android.widget.EditText; import android.widget.FrameLayout; import android.widget.Toast;
import com.google.android.gms.auth.api.signin.GoogleSignIn; import com.google.android.gms.auth.api.signin.GoogleSignInAccount; import com.google.android.gms.auth.api.signin.GoogleSignInClient; import com.google.android.gms.auth.api.signin.GoogleSignInOptions; import com.google.android.gms.common.api.ApiException; import com.google.android.gms.location.FusedLocationProviderClient; import com.google.android.gms.location.LocationServices; import com.google.android.gms.location.Priority; import com.google.android.gms.tasks.CancellationTokenSource; import com.google.android.gms.tasks.Task; import org.json.JSONObject;

public class MainActivity extends Activity {
 private static final String PREFS="sbp_padel_android",KEY_HOST="laptop_ip"; private static final int FILE_CHOOSER_REQUEST=501,GOOGLE_SIGN_IN_REQUEST=502,LOCATION_REQUEST=503; private FrameLayout root; private WebView webView; private ValueCallback<Uri[]> fileChooserCallback; private GoogleSignInClient googleSignInClient; private FusedLocationProviderClient locationClient; private String playerHost="",pendingGeoOrigin; private GeolocationPermissions.Callback pendingGeoCallback; private boolean nativeLocationPending=false;
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(6,16,18));getWindow().setNavigationBarColor(Color.BLACK);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);root=new FrameLayout(this);root.setBackgroundColor(Color.rgb(6,16,18));root.setClipToPadding(true);webView=new WebView(this);webView.setBackgroundColor(Color.rgb(6,16,18));webView.setLayoutParams(new FrameLayout.LayoutParams(-1,-1));root.addView(webView);setContentView(root);locationClient=LocationServices.getFusedLocationProviderClient(this);configureSystemUi();configureWebView();configureBackNavigation();if(BuildConfig.DEBUG){String host=getSharedPreferences(PREFS,MODE_PRIVATE).getString(KEY_HOST,"");if(host==null||host.trim().isEmpty())showHostDialog();else loadPlayer(host.trim());}else loadReleasePlayer();}
 private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
 private void configureSystemUi(){if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.R){getWindow().setDecorFitsSystemWindows(false);WindowInsetsController c=getWindow().getInsetsController();if(c!=null){c.hide(WindowInsets.Type.navigationBars());c.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);}root.setOnApplyWindowInsetsListener((v,i)->{android.graphics.Insets s=i.getInsetsIgnoringVisibility(WindowInsets.Type.statusBars()),cut=i.getInsets(WindowInsets.Type.displayCutout()),ime=i.getInsets(WindowInsets.Type.ime());boolean open=i.isVisible(WindowInsets.Type.ime());v.setPadding(Math.max(s.left,cut.left),Math.max(s.top,cut.top)+dp(4),Math.max(s.right,cut.right),open?ime.bottom:0);v.post(()->{if(webView!=null)webView.evaluateJavascript("document.documentElement.classList.toggle('sbp-keyboard-open',"+(open?"true":"false")+");"+(open?"setTimeout(function(){window.SBPAndroidRevealFocused&&window.SBPAndroidRevealFocused()},40);":""),null);});return i;});root.requestApplyInsets();}else{getWindow().getDecorView().setSystemUiVisibility(5894);}}
 private boolean hasLocation(){return Build.VERSION.SDK_INT<23||checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED;}
 private boolean isTrustedAppUri(Uri u){if(u==null)return false;if(BuildConfig.DEBUG)return "http".equalsIgnoreCase(u.getScheme())&&playerHost.equalsIgnoreCase(u.getHost())&&u.getPort()==5173;Uri configured=Uri.parse(BuildConfig.PLAYER_URL);return "https".equalsIgnoreCase(u.getScheme())&&configured.getHost()!=null&&configured.getHost().equalsIgnoreCase(u.getHost());}
 private boolean isTrustedOrigin(String raw){try{return isTrustedAppUri(Uri.parse(raw));}catch(Exception e){return false;}}
 private void configureWebView(){WebView.setWebContentsDebuggingEnabled(BuildConfig.DEBUG);WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setGeolocationEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(BuildConfig.DEBUG);s.setMixedContentMode(BuildConfig.DEBUG?WebSettings.MIXED_CONTENT_ALWAYS_ALLOW:WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setTextZoom(100);webView.setVerticalScrollBarEnabled(false);webView.setOverScrollMode(View.OVER_SCROLL_NEVER);webView.addJavascriptInterface(new AndroidBridge(),"SBPAndroid");webView.setWebChromeClient(new WebChromeClient(){@Override public boolean onShowFileChooser(WebView w,ValueCallback<Uri[]> cb,FileChooserParams p){if(fileChooserCallback!=null)fileChooserCallback.onReceiveValue(null);fileChooserCallback=cb;Intent i=p.createIntent();i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);try{startActivityForResult(i,FILE_CHOOSER_REQUEST);return true;}catch(Exception e){fileChooserCallback=null;return false;}}@Override public void onGeolocationPermissionsShowPrompt(String origin,GeolocationPermissions.Callback cb){if(!BuildConfig.DEBUG&&!isTrustedOrigin(origin)){cb.invoke(origin,false,false);return;}if(hasLocation()){cb.invoke(origin,true,false);return;}pendingGeoOrigin=origin;pendingGeoCallback=cb;requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},LOCATION_REQUEST);}});webView.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();if(isTrustedAppUri(u))return false;openExternalUri(u);return true;}@Override public void onPageFinished(WebView v,String u){super.onPageFinished(v,u);if(!BuildConfig.DEBUG&&!isTrustedOrigin(u)){v.stopLoading();Toast.makeText(MainActivity.this,"Blocked an untrusted in-app page.",Toast.LENGTH_LONG).show();return;}rehideNavigationBar();root.requestApplyInsets();}});}
 private void requestNativeLocation(){if(!hasLocation()){nativeLocationPending=true;if(Build.VERSION.SDK_INT>=23)requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},LOCATION_REQUEST);return;}try{CancellationTokenSource token=new CancellationTokenSource();locationClient.getCurrentLocation(Priority.PRIORITY_HIGH_ACCURACY,token.getToken()).addOnSuccessListener(loc->{if(loc!=null)sendLocation(loc.getLatitude(),loc.getLongitude());else locationClient.getLastLocation().addOnSuccessListener(last->{if(last!=null)sendLocation(last.getLatitude(),last.getLongitude());else sendLocationError("Phone location is unavailable. Turn Location on and try again.");}).addOnFailureListener(e->sendLocationError("Could not read phone location."));}).addOnFailureListener(e->sendLocationError("Could not read phone location."));}catch(SecurityException e){sendLocationError("Location permission is not available to SBP Padel.");}}
 private void sendLocation(double lat,double lon){if(webView!=null)webView.post(()->webView.evaluateJavascript("window.SBPNativeLocationResult&&window.SBPNativeLocationResult("+lat+","+lon+")",null));}
 private void sendLocationError(String msg){if(webView!=null){String q=JSONObject.quote(msg);webView.post(()->webView.evaluateJavascript("window.SBPNativeLocationError&&window.SBPNativeLocationError("+q+")",null));}}
 @Override public void onRequestPermissionsResult(int code,String[] p,int[] results){super.onRequestPermissionsResult(code,p,results);if(code!=LOCATION_REQUEST)return;boolean granted=hasLocation();if(pendingGeoCallback!=null&&pendingGeoOrigin!=null)pendingGeoCallback.invoke(pendingGeoOrigin,granted,false);pendingGeoCallback=null;pendingGeoOrigin=null;if(nativeLocationPending){nativeLocationPending=false;if(granted)requestNativeLocation();else sendLocationError("Location permission was denied.");}}
 private void configureBackNavigation(){if(Build.VERSION.SDK_INT>=33)getOnBackInvokedDispatcher().registerOnBackInvokedCallback(android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT,this::handleBackNavigation);}
 private void handleBackNavigation(){if(webView==null){finish();return;}webView.evaluateJavascript("(function(){try{return !!(window.SBPHandleAndroidBack&&window.SBPHandleAndroidBack())}catch(e){return false}})()",v->runOnUiThread(()->{if("true".equalsIgnoreCase(String.valueOf(v)))return;if(webView.canGoBack())webView.goBack();else finish();}));}
 public class AndroidBridge{@JavascriptInterface public void googleSignIn(String id){if(!BuildConfig.DEBUG&&!isTrustedAppUri(Uri.parse(webView.getUrl())))return;runOnUiThread(()->startGoogleSignIn(id));}@JavascriptInterface public void openExternal(String raw){runOnUiThread(()->{try{Uri u=Uri.parse(raw==null?"":raw.trim());String scheme=u.getScheme();if(!"https".equalsIgnoreCase(scheme)&&!(BuildConfig.DEBUG&&"http".equalsIgnoreCase(scheme)))return;openExternalUri(u);}catch(Exception ignored){}});}@JavascriptInterface public void requestLocation(){if(!BuildConfig.DEBUG&&!isTrustedAppUri(Uri.parse(webView.getUrl())))return;runOnUiThread(()->requestNativeLocation());}}
 private void openExternalUri(Uri u){try{String scheme=u!=null?u.getScheme():null;if(!"https".equalsIgnoreCase(scheme)&&!(BuildConfig.DEBUG&&"http".equalsIgnoreCase(scheme)))return;startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception e){Toast.makeText(this,"No app is available to open this link.",Toast.LENGTH_LONG).show();}}
 private void startGoogleSignIn(String id){if(id==null||id.trim().isEmpty()){sendGoogleError("Google sign-in is not configured.");return;}GoogleSignInOptions o=new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN).requestIdToken(id.trim()).requestEmail().build();googleSignInClient=GoogleSignIn.getClient(this,o);startActivityForResult(googleSignInClient.getSignInIntent(),GOOGLE_SIGN_IN_REQUEST);}
 private void sendGoogleCredential(String c){if(webView!=null){String q=JSONObject.quote(c);webView.post(()->webView.evaluateJavascript("window.SBPGoogleNativeResult&&window.SBPGoogleNativeResult("+q+")",null));}}
 private void sendGoogleError(String m){if(webView!=null){String q=JSONObject.quote(m);webView.post(()->webView.evaluateJavascript("window.SBPGoogleNativeError&&window.SBPGoogleNativeError("+q+")",null));}}
 private void rehideNavigationBar(){if(Build.VERSION.SDK_INT>=30){WindowInsetsController c=getWindow().getInsetsController();if(c!=null){c.hide(WindowInsets.Type.navigationBars());c.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);}}else getWindow().getDecorView().setSystemUiVisibility(5894);}
 @Override public void onWindowFocusChanged(boolean h){super.onWindowFocusChanged(h);if(h){rehideNavigationBar();root.requestApplyInsets();}}
 @Override protected void onActivityResult(int code,int result,Intent data){super.onActivityResult(code,result,data);if(code==GOOGLE_SIGN_IN_REQUEST){Task<GoogleSignInAccount> t=GoogleSignIn.getSignedInAccountFromIntent(data);try{GoogleSignInAccount a=t.getResult(ApiException.class);String c=a!=null?a.getIdToken():null;if(c==null||c.isEmpty())sendGoogleError("Google did not return an identity token.");else sendGoogleCredential(c);}catch(ApiException e){sendGoogleError(e.getStatusCode()==12501?"Google sign-in was cancelled.":"Google sign-in failed (code "+e.getStatusCode()+").");}return;}if(code!=FILE_CHOOSER_REQUEST||fileChooserCallback==null)return;fileChooserCallback.onReceiveValue(WebChromeClient.FileChooserParams.parseResult(result,data));fileChooserCallback=null;}
 private void showHostDialog(){final EditText input=new EditText(this);input.setHint("Example: 192.168.1.25");input.setSingleLine(true);input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);int pad=dp(20);FrameLayout holder=new FrameLayout(this);holder.setPadding(pad,0,pad,0);holder.addView(input,new FrameLayout.LayoutParams(-1,-2));new AlertDialog.Builder(this).setTitle("Connect to SBP Padel development server").setMessage("Enter the laptop IPv4 address shown by run_player_lan.ps1. The phone and laptop must be on the same Wi-Fi network.").setView(holder).setCancelable(false).setPositiveButton("CONNECT",(d,w)->{String host=input.getText().toString().trim();if(host.isEmpty()){showHostDialog();return;}getSharedPreferences(PREFS,MODE_PRIVATE).edit().putString(KEY_HOST,host).apply();loadPlayer(host);}).show();}
 private void loadPlayer(String host){playerHost=host;String api="http://"+host+":8000/api/v1";webView.loadUrl("http://"+host+":5173/auth-preview.html?api="+Uri.encode(api));}
 private void loadReleasePlayer(){Uri target=Uri.parse(BuildConfig.PLAYER_URL);if(!"https".equalsIgnoreCase(target.getScheme())||target.getHost()==null){Toast.makeText(this,"SBP Padel release URL is not configured securely.",Toast.LENGTH_LONG).show();return;}webView.loadUrl(target.toString());}
 @Override public void onBackPressed(){if(Build.VERSION.SDK_INT>=33)return;handleBackNavigation();}
}
