'use client';

import { useEffect, useMemo, useState } from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:8000/api/v1';
type Row={venue_id:string;venue_name:string;city:string;confirmed_completed_bookings:number;booked_hours:number;gross_paid:string;currency:string};
const iso=(d:Date)=>d.toISOString().slice(0,10);const monthStart=()=>{const d=new Date();return iso(new Date(d.getFullYear(),d.getMonth(),1))};
export default function ReportsPage(){
 const [token,setToken]=useState('');const [fromDate,setFromDate]=useState(monthStart);const [toDate,setToDate]=useState(()=>iso(new Date()));const [rows,setRows]=useState<Row[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const auth=useMemo(()=>({Authorization:`Bearer ${token}`}),[token]);
 async function load(){if(fromDate>toDate){setError('From date cannot be after To date.');return}setError('');setLoading(true);try{const r=await fetch(`${API}/admin/reports/venue-performance?from_date=${fromDate}&to_date=${toDate}`,{headers:auth,cache:'no-store'});let b:any=null;try{b=await r.json()}catch{}if(r.status===401||r.status===403){localStorage.removeItem('sbp_padel_hq_token');location.href='/hq';return}if(!r.ok)throw new Error(b?.detail||'Request failed');setRows(b)}catch(e){setError(e instanceof Error?e.message:'Unable to load report')}finally{setLoading(false)}}
 useEffect(()=>{const t=localStorage.getItem('sbp_padel_hq_token')||'';if(!t){location.href='/hq';return}setToken(t)},[]);useEffect(()=>{if(token)load()},[token]);
 const totals=useMemo(()=>rows.reduce((a,r)=>({bookings:a.bookings+r.confirmed_completed_bookings,hours:a.hours+r.booked_hours,gross:a.gross+Number(r.gross_paid||0)}),{bookings:0,hours:0,gross:0}),[rows]);
 return <main className="main"><header className="top"><div><h1>Venue Performance</h1><p>Bookings, court-hours and gross paid collections by facility.</p></div><a className="btn" href="/hq">BACK TO HQ</a></header><section className="card bookingFilters"><input aria-label="From date" type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/><input aria-label="To date" type="date" value={toDate} onChange={e=>setToDate(e.target.value)}/><button className="btn" disabled={loading} onClick={load}>{loading?'RUNNING…':'RUN REPORT'}</button></section>{error&&<div className="error">{error}</div>}<section className="grid section"><div className="card metric"><b>{totals.bookings}</b><span>Confirmed/completed bookings</span></div><div className="card metric"><b>{totals.hours}</b><span>Booked court-hours</span></div><div className="card metric"><b>PKR {totals.gross.toLocaleString()}</b><span>Gross paid collections</span></div><div className="card metric"><b>{rows.length}</b><span>Venues reported</span></div></section><section className="section"><div className="table"><table><thead><tr><th>VENUE</th><th>CITY</th><th>BOOKINGS</th><th>BOOKED HOURS</th><th>GROSS PAID</th></tr></thead><tbody>{rows.map(r=><tr key={r.venue_id}><td><b>{r.venue_name}</b></td><td>{r.city}</td><td>{r.confirmed_completed_bookings}</td><td>{r.booked_hours}</td><td>{r.currency} {r.gross_paid}</td></tr>)}{!rows.length&&!loading&&<tr><td colSpan={5}>No venue activity in the selected period.</td></tr>}</tbody></table></div></section></main>
}
