from fastapi.testclient import TestClient
from app.main import app

def login_headers(client:TestClient)->dict[str,str]:
    login=client.post('/api/v1/auth/login',json={'identifier':'player@sbppadel.local','password':'PadelDemo2026!'});assert login.status_code==200;return {'Authorization':f"Bearer {login.json()['access_token']}"}
def nishtar(client):return next(v for v in client.get('/api/v1/venues').json() if v['name']=='Nishtar Park Sports Complex')
def test_health():
    with TestClient(app) as client:r=client.get('/api/v1/health');assert r.status_code==200;assert r.json()['status']=='ok'
def test_seeded_venue_and_variable_pricing():
    with TestClient(app) as client:
        venue=nishtar(client);availability=client.get(f"/api/v1/venues/{venue['id']}/availability",params={'date':'2030-09-07'});assert availability.status_code==200;championship=next(c for c in availability.json()['courts'] if c['court_code']=='01');rates={s['start_time']:s['hourly_rate'] for s in championship['slots'] if s['hourly_rate'] is not None};assert rates['17:00']=='2000.00';assert rates['19:00']=='2200.00';assert rates['21:00']=='2000.00'
def test_policy_login_quote_booking_and_cancel():
    with TestClient(app) as client:
        headers=login_headers(client);assert client.get('/api/v1/auth/me',headers=headers).json()['role']=='player';policy=client.get('/api/v1/policies/active').json();venue=nishtar(client);detail=client.get(f"/api/v1/venues/{venue['id']}").json();court_id=next(c['id'] for c in detail['courts'] if c['code']=='01');payload={'venue_id':venue['id'],'court_id':court_id,'booking_date':'2030-09-07','slots':[{'start_time':'19:00'},{'start_time':'20:00'}]};quote=client.post('/api/v1/bookings/quote',json=payload);assert quote.status_code==200;assert quote.json()['court_fee']=='4400.00';created=client.post('/api/v1/bookings',json={**payload,'policy_version_id':policy['id'],'policy_accepted':True},headers=headers);assert created.status_code==200;assert client.post('/api/v1/bookings/quote',json=payload).status_code==409;cancelled=client.post(f"/api/v1/bookings/{created.json()['id']}/cancel",json={'reason':'Changed plans'},headers=headers);assert cancelled.status_code==200;assert cancelled.json()['slots_released'] is True;assert client.post('/api/v1/bookings/quote',json=payload).status_code==200
def test_payment_confirmation_notification_and_refund_request():
    with TestClient(app) as client:
        headers=login_headers(client);policy=client.get('/api/v1/policies/active').json();venue=nishtar(client);detail=client.get(f"/api/v1/venues/{venue['id']}").json();court_id=next(c['id'] for c in detail['courts'] if c['code']=='02');created=client.post('/api/v1/bookings',json={'venue_id':venue['id'],'court_id':court_id,'booking_date':'2030-09-08','slots':[{'start_time':'18:00'}],'policy_version_id':policy['id'],'policy_accepted':True},headers=headers);assert created.status_code==200;initiated=client.post('/api/v1/payments/initiate',json={'booking_id':created.json()['id'],'method':'wallet'},headers=headers);payment_id=initiated.json()['payment_id'];confirmed=client.post(f'/api/v1/payments/{payment_id}/simulate-success',headers=headers);assert confirmed.status_code==200;cancelled=client.post(f"/api/v1/bookings/{created.json()['id']}/cancel",json={'reason':'Unable to attend'},headers=headers);assert cancelled.status_code==200;assert cancelled.json()['refund_required'] is True;refund=client.post(f'/api/v1/payments/{payment_id}/refund',json={'reason':'Booking cancelled by player'},headers=headers);assert refund.status_code==200;assert refund.json()['status']=='requested';notifications=client.get('/api/v1/notifications/me',headers=headers).json();assert any(n['kind']=='refund_requested' for n in notifications)
