'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';

type Venue={id:string;name:string;city:string;role:string};
type Player={id:string|null;full_name:string;email:string|null;phone:string|null};
type Booking={id:string;booking_code:string;date:string;status:string;court_id:string;court_code:string|null;court_name:string;court_type:string|null;player:Player;slots:string[];total:string;currency:string;payment_status:string|null;payment_method:string|null;payment_reference:string|null;checked_in:boolean;checked_in_at:string|null};
type Block={id:string;date:string;start_time:string;end_time:string;type:string;reason:string;court_id:string|null};
type Court={id:string;code:string;name:string;court_type:string;status:'active'|'maintenance'|'closed';capacity:number;is_indoor:boolean};
type Tab='schedule'|'bookings'|'closures'|'courts';
const API=process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:8000/api/v1';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const niceDate=(iso:string)=>new Date(`${iso}T12:00:00`).toLocaleDateString('en-PK',{weekday:'short',day:'numeric',month:'short',year:'numeric'});
const paymentLabel=(v:string|null)=>v?String(v).replaceAll('_',' ').toUpperCase():'NO PAYMENT';

export default function Page(){
 const[token,setToken]=useState(''),[email,setEmail]=useState('manager@sbppadel.local'),[password,setPassword]=useState('PadelManager2026!'),[error,setError]=useState('');
 const[venues,setVenues]=useState<Venue[]>([]),[venueId,setVenueId]=useState(''),[bookings,setBookings]=useState<Booking[]>([]),[blocks,setBlocks]=useState<Block[]>([]),[courts,setCourts]=useState<Court[]>([]),[tab,setTab]=useState<Tab>('schedule');
 const[date,setDate]=useState(today()),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState(''),[selected,setSelected]=useState<Booking|null>(null),[loading,setLoading]=useState(false);
 const[blockDate,setBlockDate]=useState(today()),[blockStart,setBlockStart]=useState('19:00'),[blockEnd,setBlockEnd]=useState('21:00'),[blockCourt,setBlockCourt]=useState(''),[blockType,setBlockType]=useState('maintenance'),[blockReason,setBlockReason]=useState('Scheduled maintenance');
 const auth=useMemo(()=>({Authorization:`Bearer ${token}`}),[token]),currentVenue=venues.find(v=>v.id===venueId),canManage=currentVenue?.role==='manager'||currentVenue?.role==='admin';
 async function api(path:string,options:RequestInit={}){const res=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?auth:{}),...(options.headers||{})},cache:'no-store'});let body:any=null;try{body=await res.json()}catch{}if(!res.ok)throw new Error(typeof body?.detail==='string'?body.detail:`Request failed (${res.status})`);return body}
 async function login(e:FormEvent){e.preventDefault();setError('');try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({identifier:email,password})});setToken(d.access_token);localStorage.setItem('sbp_padel_ops_token',d.access_token)}catch(x){setError(x instanceof Error?x.message:'Login failed')}}
 async function loadBookings(id=venueId,day=date){if(!id)return;setLoading(true);try{const params=new URLSearchParams({venue_id:id});if(tab==='schedule'&&day)params.set('booking_date',day);if(query.trim())params.set('q',query.trim());if(statusFilter)params.set('status',statusFilter);setBookings(await api(`/operations/bookings?${params}`))}finally{setLoading(false)}}
 async function loadBlocks(id=venueId){if(id)setBlocks(await api(`/operations/blocks?venue_id=${id}`))}async function loadCourts(id=venueId){if(id)setCourts(await api(`/operations/courts?venue_id=${id}`))}
 useEffect(()=>{const s=localStorage.getItem('sbp_padel_ops_token');if(s)setToken(s)},[]);
 useEffect(()=>{if(!token)return;api('/operations/my-venues').then((v:Venue[])=>{setVenues(v);if(v[0])setVenueId(v[0].id)}).catch(()=>{setToken('');localStorage.removeItem('sbp_padel_ops_token')})},[token]);
 useEffect(()=>{if(!token||!venueId)return;Promise.all([loadBookings(venueId,date),loadBlocks(venueId),loadCourts(venueId)]).catch(e=>setError(e.message))},[token,venueId]);
 useEffect(()=>{if(!token||!venueId)return;const t=setTimeout(()=>loadBookings(venueId,date).catch(e=>setError(e.message)),180);return()=>clearTimeout(t)},[date,query,statusFilter,tab]);
 async function checkIn(id:string){try{await api(`/operations/bookings/${id}/check-in`,{method:'POST',body:'{}'});setBookings(r=>r.map(x=>x.id===id?{...x,checked_in:true,checked_in_at:new Date().toISOString()}:x));setSelected(s=>s?.id===id?{...s,checked_in:true,checked_in_at:new Date().toISOString()}:s)}catch(e){setError(e instanceof Error?e.message:'Check-in failed')}}
 async function createBlock(e:FormEvent){e.preventDefault();setError('');try{await api('/operations/blocks',{method:'POST',body:JSON.stringify({venue_id:venueId,court_id:blockCourt||null,block_date:blockDate,start_time:blockStart,end_time:blockEnd,block_type:blockType,reason:blockReason})});await Promise.all([loadBlocks(),loadBookings()])}catch(x){setError(x instanceof Error?x.message:'Closure failed')}}
 async function removeBlock(id:string){try{await api(`/operations/blocks/${id}`,{method:'DELETE'});await Promise.all([loadBlocks(),loadBookings()])}catch(x){setError(x instanceof Error?x.message:'Unable to remove closure')}}
 async function setCourtStatus(id:string,status:Court['status']){try{await api(`/operations/courts/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});setCourts(rows=>rows.map(c=>c.id===id?{...c,status}:c))}catch(x){setError(x instanceof Error?x.message:'Unable to change court status')}}
 function signOut(){localStorage.removeItem('sbp_padel_ops_token');setToken('');setVenues([]);setVenueId('')}
 if(!token)return <main className="login"><form className="loginCard" onSubmit={login}><div className="brand"><small>SPORTS BOARD PUNJAB</small>SBP Padel Operations</div><h1>Staff sign in</h1><p>Venue management and front-desk operations.</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button className="btn">SIGN IN</button>{error&&<div className="error">{error}</div>}</form></main>;
 const confirmed=bookings.filter(b=>['confirmed','rescheduled'].includes(b.status)).length,checked=bookings.filter(b=>b.checked_in).length,paid=bookings.filter(b=>b.payment_status==='paid').length,title=tab==='schedule'?'Court Schedule':tab==='bookings'?'All Bookings':tab==='closures'?'Closures & Maintenance':'Court Operations';
 const scheduleCourts=courts.map(c=>({court:c,rows:bookings.filter(b=>b.court_id===c.id).sort((a,b)=>(a.slots[0]||'').localeCompare(b.slots[0]||''))}));
 return <div className="shell"><aside className="sidebar"><div className="brand"><small>SPORTS BOARD PUNJAB</small>SBP Padel</div><div className="nav"><button className={tab==='schedule'?'active':''} onClick={()=>setTab('schedule')}>Court Schedule</button><button className={tab==='bookings'?'active':''} onClick={()=>setTab('bookings')}>Bookings</button><button className={tab==='closures'?'active':''} onClick={()=>setTab('closures')}>Closures & Maintenance</button><button className={tab==='courts'?'active':''} onClick={()=>setTab('courts')}>Courts</button></div><div className="sideFoot"><span>{currentVenue?.role?.toUpperCase()||'OPERATIONS'}</span><button onClick={signOut}>Sign out</button></div></aside><main className="main"><header className="top"><div><h1>{title}</h1><p>{currentVenue?`${currentVenue.name} · ${currentVenue.city}`:'Loading assigned venue...'}</p></div><div className="toolbar"><select value={venueId} onChange={e=>setVenueId(e.target.value)}>{venues.map(v=><option key={v.id} value={v.id}>{v.name} · {v.city}</option>)}</select><div className="pill">{currentVenue?.role?.toUpperCase()||'OPERATIONS'}</div></div></header>{error&&<div className="error errorBar">{error}<button onClick={()=>setError('')}>×</button></div>}
 {(tab==='schedule'||tab==='bookings')&&<><section className="opsFilters"><div><label>{tab==='schedule'?'Schedule date':'Date (optional)'}</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div><label>Search</label><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Booking, player, email or phone"/></div><div><label>Status</label><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All statuses</option><option value="pending_payment">Pending payment</option><option value="confirmed">Confirmed</option><option value="rescheduled">Rescheduled</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div><button className="btn" onClick={()=>loadBookings()}>{loading?'LOADING…':'REFRESH'}</button></section><section className="grid"><div className="card metric"><b>{bookings.length}</b><span>{tab==='schedule'?'Bookings on date':'Bookings loaded'}</span></div><div className="card metric"><b>{confirmed}</b><span>Active bookings</span></div><div className="card metric"><b>{paid}</b><span>Paid</span></div><div className="card metric"><b>{checked}</b><span>Checked in</span></div></section></>}
 {tab==='schedule'&&<section className="section"><div className="sectionHead"><div><h2>{niceDate(date)}</h2><p className="sectionNote">Live operational view by court. Select a booking for player, payment and check-in details.</p></div></div><div className="scheduleGrid">{scheduleCourts.map(({court,rows})=><article className="card scheduleCourt" key={court.id}><div className="scheduleCourtHead"><div><small>COURT {court.code}</small><h3>{court.name}</h3></div><span className={`courtState ${court.status}`}>{court.status.toUpperCase()}</span></div><div className="scheduleList">{rows.length?rows.map(b=><button className={`scheduleBooking ${b.checked_in?'checked':''}`} key={b.id} onClick={()=>setSelected(b)}><span className="scheduleTime">{b.slots.join(', ')}</span><b>{b.player.full_name}</b><small>{b.booking_code} · {b.status.replaceAll('_',' ')}</small><em>{b.checked_in?'CHECKED IN':paymentLabel(b.payment_status)}</em></button>):<div className="emptySchedule">No bookings</div>}</div></article>)}</div></section>}
 {tab==='bookings'&&<section className="section"><div className="table"><table><thead><tr><th>BOOKING</th><th>PLAYER</th><th>COURT</th><th>DATE / TIME</th><th>STATUS</th><th>PAYMENT</th><th>CHECK-IN</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id} onClick={()=>setSelected(b)} className="clickRow"><td><b>{b.booking_code}</b></td><td><b>{b.player.full_name}</b><small className="cellSub">{b.player.phone||b.player.email||'No contact'}</small></td><td>{b.court_name}</td><td>{b.date}<small className="cellSub">{b.slots.join(', ')}</small></td><td><span className="status">{b.status.replaceAll('_',' ').toUpperCase()}</span></td><td>{paymentLabel(b.payment_status)}<small className="cellSub">{b.currency} {b.total}</small></td><td>{b.checked_in?<span className="status">CHECKED IN</span>:['confirmed','rescheduled'].includes(b.status)?<button className="btn" onClick={e=>{e.stopPropagation();checkIn(b.id)}}>CHECK IN</button>:'—'}</td></tr>)}</tbody></table></div></section>}
 {tab==='closures'&&<><section className="card closureForm"><div><h2>Block booking time</h2><p>Maintenance, official events, weather or operational closures remove affected slots from player booking immediately.</p></div>{canManage?<form onSubmit={createBlock}><label>Date<input type="date" value={blockDate} onChange={e=>setBlockDate(e.target.value)}/></label><label>Court<select value={blockCourt} onChange={e=>setBlockCourt(e.target.value)}><option value="">All courts</option>{courts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>From<input type="time" value={blockStart} onChange={e=>setBlockStart(e.target.value)}/></label><label>To<input type="time" value={blockEnd} onChange={e=>setBlockEnd(e.target.value)}/></label><label>Type<select value={blockType} onChange={e=>setBlockType(e.target.value)}><option value="maintenance">Maintenance</option><option value="official_event">Official event</option><option value="weather">Weather</option><option value="private_closure">Private closure</option><option value="other">Other</option></select></label><label className="wide">Reason<input value={blockReason} onChange={e=>setBlockReason(e.target.value)}/></label><button className="btn">CREATE CLOSURE</button></form>:<div className="readOnly">Operator access is view-only for closures.</div>}</section><section className="section"><div className="sectionHead"><h2>Active closures</h2><button className="btn" onClick={()=>loadBlocks()}>REFRESH</button></div><div className="table"><table><thead><tr><th>DATE</th><th>TIME</th><th>TYPE</th><th>REASON</th><th>SCOPE</th><th>ACTION</th></tr></thead><tbody>{blocks.map(b=><tr key={b.id}><td>{b.date}</td><td>{b.start_time}–{b.end_time}</td><td>{b.type.replace('_',' ')}</td><td>{b.reason}</td><td>{b.court_id?courts.find(c=>c.id===b.court_id)?.name||'Court':'All courts'}</td><td>{canManage?<button className="btn danger" onClick={()=>removeBlock(b.id)}>REMOVE</button>:'View only'}</td></tr>)}</tbody></table></div></section></>}
 {tab==='courts'&&<section className="section"><div className="sectionHead"><div><h2>Court status</h2><p className="sectionNote">Maintenance or Closed courts disappear from player availability immediately.</p></div><button className="btn" onClick={()=>loadCourts()}>REFRESH</button></div><div className="courtGrid">{courts.map(c=><article className="card courtCard" key={c.id}><div><small>COURT {c.code}</small><h3>{c.name}</h3><p>{c.court_type} · Capacity {c.capacity}</p></div><span className={`courtState ${c.status}`}>{c.status.toUpperCase()}</span>{canManage?<select value={c.status} onChange={e=>setCourtStatus(c.id,e.target.value as Court['status'])}><option value="active">Active</option><option value="maintenance">Maintenance</option><option value="closed">Closed</option></select>:<div className="readOnly">View only</div>}</article>)}</div></section>}
 </main>{selected&&<div className="drawerBackdrop" onClick={()=>setSelected(null)}><aside className="bookingDrawer" onClick={e=>e.stopPropagation()}><button className="drawerClose" onClick={()=>setSelected(null)}>×</button><small className="eyebrow">BOOKING DETAILS</small><h2>{selected.booking_code}</h2><div className="drawerStatus"><span className="status">{selected.status.replaceAll('_',' ').toUpperCase()}</span>{selected.checked_in&&<span className="status">CHECKED IN</span>}</div><section><label>Player</label><b>{selected.player.full_name}</b><p>{selected.player.phone||'No phone'}<br/>{selected.player.email||'No email'}</p></section><section><label>Court & session</label><b>{selected.court_name}</b><p>{niceDate(selected.date)}<br/>{selected.slots.join(', ')}</p></section><section><label>Payment</label><b>{paymentLabel(selected.payment_status)}</b><p>{selected.currency} {selected.total}{selected.payment_method?` · ${selected.payment_method}`:''}<br/>{selected.payment_reference||'No provider reference'}</p></section>{!selected.checked_in&&['confirmed','rescheduled'].includes(selected.status)&&<button className="btn drawerAction" onClick={()=>checkIn(selected.id)}>CHECK IN PLAYER</button>}</aside></div>}</div>;
}
