'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';

type Venue={id:string;name:string;city:string;role:string};
type Booking={id:string;booking_code:string;date:string;status:string;slots:string[];total:string;currency:string;checked_in:boolean};
type Block={id:string;date:string;start_time:string;end_time:string;type:string;reason:string;court_id:string|null};
type Court={id:string;code:string;name:string;court_type:string;status:'active'|'maintenance'|'closed';capacity:number;is_indoor:boolean};
type Tab='overview'|'closures'|'courts';
const API=process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:8000/api/v1';

export default function Page(){
 const[token,setToken]=useState(''),[email,setEmail]=useState('manager@sbppadel.local'),[password,setPassword]=useState('PadelManager2026!'),[error,setError]=useState('');
 const[venues,setVenues]=useState<Venue[]>([]),[venueId,setVenueId]=useState(''),[bookings,setBookings]=useState<Booking[]>([]),[blocks,setBlocks]=useState<Block[]>([]),[courts,setCourts]=useState<Court[]>([]),[tab,setTab]=useState<Tab>('overview');
 const[blockDate,setBlockDate]=useState('2026-09-10'),[blockStart,setBlockStart]=useState('19:00'),[blockEnd,setBlockEnd]=useState('21:00'),[blockType,setBlockType]=useState('maintenance'),[blockReason,setBlockReason]=useState('Scheduled maintenance');
 const auth=useMemo(()=>({Authorization:`Bearer ${token}`}),[token]),currentVenue=venues.find(v=>v.id===venueId),canManage=currentVenue?.role==='manager'||currentVenue?.role==='admin';
 async function api(path:string,options:RequestInit={}){const res=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?auth:{}),...(options.headers||{})}});if(!res.ok)throw new Error((await res.json()).detail||'Request failed');return res.json()}
 async function login(e:FormEvent){e.preventDefault();setError('');try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({identifier:email,password})});setToken(d.access_token);localStorage.setItem('sbp_padel_ops_token',d.access_token)}catch(x){setError(x instanceof Error?x.message:'Login failed')}}
 async function loadBookings(id=venueId){if(id)setBookings(await api(`/operations/bookings?venue_id=${id}`))}async function loadBlocks(id=venueId){if(id)setBlocks(await api(`/operations/blocks?venue_id=${id}`))}async function loadCourts(id=venueId){if(id)setCourts(await api(`/operations/courts?venue_id=${id}`))}
 useEffect(()=>{const s=localStorage.getItem('sbp_padel_ops_token');if(s)setToken(s)},[]);useEffect(()=>{if(!token)return;api('/operations/my-venues').then((v:Venue[])=>{setVenues(v);if(v[0])setVenueId(v[0].id)}).catch(()=>{setToken('');localStorage.removeItem('sbp_padel_ops_token')})},[token]);useEffect(()=>{if(!token||!venueId)return;Promise.all([loadBookings(venueId),loadBlocks(venueId),loadCourts(venueId)]).catch(e=>setError(e.message))},[token,venueId]);
 async function checkIn(id:string){try{await api(`/operations/bookings/${id}/check-in`,{method:'POST',body:'{}'});setBookings(r=>r.map(x=>x.id===id?{...x,checked_in:true}:x))}catch(e){setError(e instanceof Error?e.message:'Check-in failed')}}
 async function createBlock(e:FormEvent){e.preventDefault();setError('');try{await api('/operations/blocks',{method:'POST',body:JSON.stringify({venue_id:venueId,block_date:blockDate,start_time:blockStart,end_time:blockEnd,block_type:blockType,reason:blockReason})});await loadBlocks()}catch(x){setError(x instanceof Error?x.message:'Closure failed')}}async function removeBlock(id:string){try{await api(`/operations/blocks/${id}`,{method:'DELETE'});await loadBlocks()}catch(x){setError(x instanceof Error?x.message:'Unable to remove closure')}}
 async function setCourtStatus(id:string,status:Court['status']){try{await api(`/operations/courts/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});setCourts(rows=>rows.map(c=>c.id===id?{...c,status}:c))}catch(x){setError(x instanceof Error?x.message:'Unable to change court status')}}
 if(!token)return <main className="login"><form className="loginCard" onSubmit={login}><div className="brand"><small>SPORTS BOARD PUNJAB</small>SBP Padel Operations</div><h1>Staff sign in</h1><p>Administration and venue operations portal.</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button className="btn">SIGN IN</button>{error&&<div className="error">{error}</div>}</form></main>;
 const confirmed=bookings.filter(b=>b.status==='confirmed').length,checked=bookings.filter(b=>b.checked_in).length,title=tab==='overview'?'Venue Operations':tab==='closures'?'Closures & Maintenance':'Court Operations';
 return <div className="shell"><aside className="sidebar"><div className="brand"><small>SPORTS BOARD PUNJAB</small>SBP Padel</div><div className="nav"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='closures'?'active':''} onClick={()=>setTab('closures')}>Closures & Maintenance</button><button className={tab==='courts'?'active':''} onClick={()=>setTab('courts')}>Courts</button><button>Pricing</button><button>Reports</button></div></aside><main className="main"><header className="top"><div><h1>{title}</h1><p>{currentVenue?`${currentVenue.name} · ${currentVenue.city}`:'Loading assigned venue...'}</p></div><div className="toolbar"><select value={venueId} onChange={e=>setVenueId(e.target.value)}>{venues.map(v=><option key={v.id} value={v.id}>{v.name} · {v.city}</option>)}</select><div className="pill">{currentVenue?.role?.toUpperCase()||'OPERATIONS'}</div></div></header>{error&&<div className="error">{error}</div>}
 {tab==='overview'&&<><section className="grid"><div className="card metric"><b>{bookings.length}</b><span>Bookings loaded</span></div><div className="card metric"><b>{confirmed}</b><span>Confirmed</span></div><div className="card metric"><b>{checked}</b><span>Checked in</span></div><div className="card metric"><b>{blocks.length}</b><span>Active closures</span></div></section><section className="section"><div className="sectionHead"><h2>Bookings</h2><button className="btn" onClick={()=>loadBookings()}>REFRESH</button></div><div className="table"><table><thead><tr><th>BOOKING</th><th>DATE</th><th>TIME</th><th>STATUS</th><th>AMOUNT</th><th>ACTION</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id}><td><b>{b.booking_code}</b></td><td>{b.date}</td><td>{b.slots.join(', ')}</td><td><span className="status">{b.status.toUpperCase()}</span></td><td>{b.currency} {b.total}</td><td>{b.checked_in?<span className="status">CHECKED IN</span>:b.status==='confirmed'?<button className="btn" onClick={()=>checkIn(b.id)}>CHECK IN</button>:'—'}</td></tr>)}</tbody></table></div></section></>}
 {tab==='closures'&&<><section className="card closureForm"><div><h2>Block booking time</h2><p>Maintenance, official events, weather or other operational closures remove affected slots from player booking immediately.</p></div>{canManage?<form onSubmit={createBlock}><label>Date<input type="date" value={blockDate} onChange={e=>setBlockDate(e.target.value)}/></label><label>From<input type="time" value={blockStart} onChange={e=>setBlockStart(e.target.value)}/></label><label>To<input type="time" value={blockEnd} onChange={e=>setBlockEnd(e.target.value)}/></label><label>Type<select value={blockType} onChange={e=>setBlockType(e.target.value)}><option value="maintenance">Maintenance</option><option value="official_event">Official event</option><option value="weather">Weather</option><option value="private_closure">Private closure</option><option value="other">Other</option></select></label><label className="wide">Reason<input value={blockReason} onChange={e=>setBlockReason(e.target.value)}/></label><button className="btn">CREATE CLOSURE</button></form>:<div className="readOnly">Operator access is view-only for closures.</div>}</section><section className="section"><div className="sectionHead"><h2>Active closures</h2><button className="btn" onClick={()=>loadBlocks()}>REFRESH</button></div><div className="table"><table><thead><tr><th>DATE</th><th>TIME</th><th>TYPE</th><th>REASON</th><th>SCOPE</th><th>ACTION</th></tr></thead><tbody>{blocks.map(b=><tr key={b.id}><td>{b.date}</td><td>{b.start_time}–{b.end_time}</td><td>{b.type.replace('_',' ')}</td><td>{b.reason}</td><td>{b.court_id?'Court':'All courts'}</td><td>{canManage?<button className="btn danger" onClick={()=>removeBlock(b.id)}>REMOVE</button>:'View only'}</td></tr>)}</tbody></table></div></section></>}
 {tab==='courts'&&<section className="section"><div className="sectionHead"><div><h2>Court status</h2><p className="sectionNote">Maintenance or Closed courts disappear from player availability immediately.</p></div><button className="btn" onClick={()=>loadCourts()}>REFRESH</button></div><div className="courtGrid">{courts.map(c=><article className="card courtCard" key={c.id}><div><small>COURT {c.code}</small><h3>{c.name}</h3><p>{c.court_type} · Capacity {c.capacity}</p></div><span className={`courtState ${c.status}`}>{c.status.toUpperCase()}</span>{canManage?<select value={c.status} onChange={e=>setCourtStatus(c.id,e.target.value as Court['status'])}><option value="active">Active</option><option value="maintenance">Maintenance</option><option value="closed">Closed</option></select>:<div className="readOnly">View only</div>}</article>)}</div></section>}
 </main></div>;
}
