'use client';

import { FormEvent, useEffect, useState } from 'react';

type Venue={id:string;name:string;city:string;role:string};
type Player={id:string;full_name:string;email:string|null;phone:string|null;temporary_password?:string;message?:string};
const API=process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:8000/api/v1';

export default function PlayersPage(){
 const[token,setToken]=useState(''),[venues,setVenues]=useState<Venue[]>([]),[venueId,setVenueId]=useState(''),[query,setQuery]=useState(''),[rows,setRows]=useState<Player[]>([]),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[created,setCreated]=useState<Player|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const currentVenue=venues.find(v=>v.id===venueId);
 async function api<T=unknown>(path:string,options:RequestInit={}):Promise<T>{const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},cache:'no-store'});let b:any=null;try{b=await r.json()}catch{}if(!r.ok)throw new Error(typeof b?.detail==='string'?b.detail:`Request failed (${r.status})`);return b as T}
 useEffect(()=>{const t=localStorage.getItem('sbp_padel_ops_token')||'';setToken(t)},[]);
 useEffect(()=>{if(!token)return;api<Venue[]>('/operations/my-venues').then(v=>{setVenues(v);if(v[0])setVenueId(v[0].id)}).catch(()=>location.href='/')},[token]);
 async function search(){setError('');setCreated(null);if(query.trim().length<2){setError('Enter at least 2 characters.');return}setLoading(true);try{setRows(await api<Player[]>(`/operations/players/search?venue_id=${venueId}&q=${encodeURIComponent(query.trim())}`))}catch(e){setError(e instanceof Error?e.message:'Search failed')}finally{setLoading(false)}}
 async function register(e:FormEvent){e.preventDefault();setError('');setCreated(null);try{const p=await api<Player>('/operations/players',{method:'POST',body:JSON.stringify({venue_id:venueId,full_name:name,email:email||null,phone:phone||null})});setCreated(p);setRows(r=>[p,...r.filter(x=>x.id!==p.id)]);setName('');setEmail('');setPhone('');setQuery(p.email||p.phone||p.full_name)}catch(e){setError(e instanceof Error?e.message:'Unable to create player')}}
 function signOut(){localStorage.removeItem('sbp_padel_ops_token');location.href='/'}
 if(!token)return <main className="login"><div className="loginCard"><h1>Player management</h1><p>Open the main operations console and sign in first.</p><a className="btn" href="/">BACK TO SIGN IN</a></div></main>;
 return <div className="shell playersShell"><aside className="sidebar"><div className="brand"><small>SPORTS BOARD PUNJAB</small>SBP Padel</div><div className="nav"><a href="/">Operations Console</a><a className="active" href="/players">Players</a></div><div className="sideFoot"><span>{currentVenue?.role?.toUpperCase()||'OPERATIONS'}</span><button onClick={signOut}>Sign out</button></div></aside><main className="main"><header className="top"><div><h1>Players</h1><p>{currentVenue?`${currentVenue.name} · ${currentVenue.city}`:'Register and find player accounts for front-desk bookings.'}</p></div><div className="playerTopActions"><select value={venueId} onChange={e=>setVenueId(e.target.value)}>{venues.map(v=><option key={v.id} value={v.id}>{v.name} · {v.city}</option>)}</select><div className="pill">{currentVenue?.role?.toUpperCase()||'OPERATIONS'}</div><a className="btn" href="/">BACK TO OPERATIONS</a></div></header>{error&&<div className="error errorBar">{error}<button onClick={()=>setError('')}>×</button></div>}{created&&<section className="card playerCreateResult"><small className="eyebrow">PLAYER ACCOUNT CREATED</small><h2>{created.full_name}</h2><p>{created.email||created.phone}</p><div className="tempPassword">Temporary password: <b>{created.temporary_password}</b><br/>Share this once with the player. They can use it to sign in to the player app.</div></section>}<div className="playerMgmtGrid"><section className="card formCard playerMgmtCard"><h2>Register new player</h2><p className="sectionNote">Use this when a walk-in player does not already have an SBP Padel account.</p><form className="stackForm" onSubmit={register}><label>Full name<input required minLength={2} value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Optional if phone provided"/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Optional if email provided"/></label><button className="btn bigBtn">CREATE PLAYER ACCOUNT</button></form></section><section className="card formCard playerMgmtCard"><h2>Find existing player</h2><p className="sectionNote">Search before creating a new account to avoid duplicates.</p><div className="inlineField"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();search()}}} placeholder="Name, email or phone"/><button className="btn" onClick={search}>{loading?'SEARCHING…':'SEARCH'}</button></div>{rows.length?<div className="playerSearchResults">{rows.map(p=><div className="playerSearchRow" key={p.id}><div><b>{p.full_name}</b><span>{p.phone||p.email||'No contact'}</span></div><small>PLAYER</small></div>)}</div>:<div className="playersEmpty">Search for a player, or register a new walk-in account.</div>}</section></div></main></div>
}
