'use client';

import { FormEvent, useEffect, useState } from 'react';
type Venue={id:string;name:string;city:string;is_active:boolean;opening_time:string;closing_time:string}; type Court={id:string;code:string;name:string;court_type:string;status:string}; type Staff={id:string;full_name:string;email:string;role:string;is_active:boolean}; type Assignment={id:string;user_id:string;user_name:string;user_email:string;venue_id:string;venue_name:string;role:string}; type Pricing={id:string;venue_id:string;court_id:string|null;court_type:string|null;valid_from:string|null;valid_to:string|null;weekdays:number[];start_time:string;end_time:string;hourly_rate:string;currency:string;priority:number;is_active:boolean};
const API=process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:8000/api/v1'; const weekdays=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
export default function ProvisioningPage(){
 const[token,setToken]=useState(''),[venues,setVenues]=useState<Venue[]>([]),[venueId,setVenueId]=useState(''),[courts,setCourts]=useState<Court[]>([]),[staff,setStaff]=useState<Staff[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[pricing,setPricing]=useState<Pricing[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''); const[newCourt,setNewCourt]=useState({code:'',name:'',court_type:'Standard',capacity:'4',is_indoor:false}); const[rule,setRule]=useState({court_id:'',valid_from:'',valid_to:'',start_time:'18:00',end_time:'22:00',hourly_rate:'2200',priority:'200',weekdays:[0,1,2,3,4,5,6] as number[]}); const[assignment,setAssignment]=useState({user_id:'',role:'manager'}); const currentVenue=venues.find(v=>v.id===venueId);
 async function api<T=unknown>(path:string,options:RequestInit={}):Promise<T>{const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},cache:'no-store'});let b:any=null;try{b=await r.json()}catch{}if(!r.ok)throw new Error(typeof b?.detail==='string'?b.detail:`Request failed (${r.status})`);return b as T}
 async function reload(){const[v,s,a]=await Promise.all([api<Venue[]>('/admin/venues'),api<Staff[]>('/admin/staff'),api<Assignment[]>('/admin/staff-assignments')]);setVenues(v);setStaff(s);setAssignments(a);if(venueId&&!v.some(x=>x.id===venueId))setVenueId(v[0]?.id||'')}
 async function reloadVenue(){if(!venueId)return;const[c,p]=await Promise.all([api<Court[]>(`/admin/venues/${venueId}/courts`),api<Pricing[]>(`/admin/pricing-rules?venue_id=${venueId}`)]);setCourts(c);setPricing(p)}
 useEffect(()=>{const t=localStorage.getItem('sbp_padel_hq_token')||'';if(!t){location.href='/hq';return}setToken(t)},[]); useEffect(()=>{if(!token)return;reload().then(()=>api<Venue[]>('/admin/venues')).then(v=>{if(v[0])setVenueId(v[0].id)}).catch(e=>setError(e.message))},[token]); useEffect(()=>{if(token&&venueId)reloadVenue().catch(e=>setError(e.message))},[token,venueId]);
 async function addCourt(e:FormEvent){e.preventDefault();try{await api(`/admin/venues/${venueId}/courts`,{method:'POST',body:JSON.stringify({...newCourt,capacity:Number(newCourt.capacity)})});await reloadVenue();setNewCourt({code:'',name:'',court_type:'Standard',capacity:'4',is_indoor:false});setNotice('Court added. It remains unbookable until bookable hours are defined.')}catch(e){setError(e instanceof Error?e.message:'Unable to add court')}}
 async function deleteCourt(id:string){if(!confirm('Delete this unused court? Courts with booking history cannot be deleted.'))return;try{await api(`/admin/courts/${id}`,{method:'DELETE'});await reloadVenue();setNotice('Unused court deleted.')}catch(e){setError(e instanceof Error?e.message:'Unable to delete court')}}
 function toggleDay(day:number){setRule(r=>({...r,weekdays:r.weekdays.includes(day)?r.weekdays.filter(x=>x!==day):[...r.weekdays,day].sort()}))}
 async function addRule(e:FormEvent){e.preventDefault();if(!rule.start_time.endsWith(':00')||!rule.end_time.endsWith(':00')){setError('Bookable hours must start and end on whole hours.');return}try{await api('/admin/pricing-rules',{method:'POST',body:JSON.stringify({venue_id:venueId,court_id:rule.court_id||null,court_type:null,valid_from:rule.valid_from||null,valid_to:rule.valid_to||null,weekdays:rule.weekdays,start_time:rule.start_time,end_time:rule.end_time,hourly_rate:Number(rule.hourly_rate),currency:'PKR',priority:Number(rule.priority)})});await reloadVenue();setNotice('Bookable hours and price saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to add rule')}}
 async function removeRule(id:string){try{await api(`/admin/pricing-rules/${id}`,{method:'DELETE'});await reloadVenue();setNotice('Bookable-hours rule disabled.')}catch(e){setError(e instanceof Error?e.message:'Unable to disable rule')}}
 async function assignStaff(e:FormEvent){e.preventDefault();if(!assignment.user_id){setError('Select a manager or operator.');return}try{await api('/admin/staff-assignments',{method:'POST',body:JSON.stringify({user_id:assignment.user_id,venue_id:venueId,role:assignment.role})});await reload();setNotice('Venue assignment saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to assign staff')}}
 async function removeAssignment(id:string){if(!confirm('Remove this staff member from the venue?'))return;try{await api(`/admin/staff-assignments/${id}`,{method:'DELETE'});await reload();setNotice('Venue assignment removed.')}catch(e){setError(e instanceof Error?e.message:'Unable to remove assignment')}}
 async function toggleVenue(){if(!currentVenue)return;try{await api(`/admin/venues/${venueId}/status`,{method:'PATCH',body:JSON.stringify({is_active:!currentVenue.is_active})});await reload();setNotice(`Venue ${currentVenue.is_active?'deactivated':'activated'}.`)}catch(e){setError(e instanceof Error?e.message:'Unable to change venue status')}}
 async function deleteVenue(){if(!currentVenue||!confirm('Permanently delete this empty venue? This is allowed only when it has no booking history, courts or active staff assignments.'))return;try{await api(`/admin/venues/${venueId}`,{method:'DELETE'});await reload();setNotice('Empty venue deleted.')}catch(e){setError(e instanceof Error?e.message:'Unable to delete venue')}}
 const venueAssignments=assignments.filter(a=>a.venue_id===venueId);
 return <div className="hqProvision"><header className="top"><div><h1>Venue Provisioning</h1><p>Turn a facility into a complete bookable SBP Padel venue, with safe rollback controls for test/setup data.</p></div><div className="toolbar"><select value={venueId} onChange={e=>setVenueId(e.target.value)}>{venues.map(v=><option key={v.id} value={v.id}>{v.name} · {v.city}</option>)}</select><a className="btn" href="/hq">BACK TO HQ</a></div></header>{error&&<div className="error errorBar">{error}<button onClick={()=>setError('')}>×</button></div>}{notice&&<div className="noticeBar">{notice}<button onClick={()=>setNotice('')}>×</button></div>}{currentVenue&&<section className="card provisionHero"><div><small>SELECTED VENUE</small><h2>{currentVenue.name}</h2><p>{currentVenue.city} · {currentVenue.opening_time}–{currentVenue.closing_time}</p></div><div><span className={`status ${currentVenue.is_active?'':'inactiveState'}`}>{currentVenue.is_active?'ACTIVE':'INACTIVE'}</span><button className="btn secondaryBtn" onClick={toggleVenue}>{currentVenue.is_active?'DEACTIVATE':'ACTIVATE'}</button><button className="btn danger" onClick={deleteVenue}>DELETE EMPTY VENUE</button></div></section>}
 <section className="provisionSteps"><article className="card provisionStep"><span className="stepNo">1</span><h2>Add courts</h2><p>Unused setup courts can be deleted. Once a court has booking history it is preserved and should be Closed instead.</p><form className="stackForm" onSubmit={addCourt}><div className="formGrid"><label>Code<input required value={newCourt.code} onChange={e=>setNewCourt({...newCourt,code:e.target.value})}/></label><label>Name<input required value={newCourt.name} onChange={e=>setNewCourt({...newCourt,name:e.target.value})}/></label><label>Court type<input required value={newCourt.court_type} onChange={e=>setNewCourt({...newCourt,court_type:e.target.value})}/></label><label>Capacity<input type="number" min="1" max="20" value={newCourt.capacity} onChange={e=>setNewCourt({...newCourt,capacity:e.target.value})}/></label></div><label className="checkLine"><input type="checkbox" checked={newCourt.is_indoor} onChange={e=>setNewCourt({...newCourt,is_indoor:e.target.checked})}/><span>Indoor court</span></label><button className="btn">ADD COURT</button></form><div className="provisionList">{courts.map(c=><div key={c.id}><b>{c.code} · {c.name}</b><span>{c.court_type} · {c.status.toUpperCase()}</span><button onClick={()=>deleteCourt(c.id)}>DELETE IF UNUSED</button></div>)}{!courts.length&&<em>No courts configured.</em>}</div></article>
 <article className="card provisionStep"><span className="stepNo">2</span><h2>Bookable Hours & Pricing</h2><p>These rules are the booking schedule. Disable a rule to remove its uncovered hours from booking.</p><form className="stackForm" onSubmit={addRule}><label>Court scope<select value={rule.court_id} onChange={e=>setRule({...rule,court_id:e.target.value})}><option value="">All courts</option>{courts.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></label><div className="formGrid"><label>Valid from<input type="date" value={rule.valid_from} onChange={e=>setRule({...rule,valid_from:e.target.value})}/></label><label>Valid to<input type="date" value={rule.valid_to} onChange={e=>setRule({...rule,valid_to:e.target.value})}/></label><label>Bookable from<input type="time" step={3600} value={rule.start_time} onChange={e=>setRule({...rule,start_time:e.target.value})}/></label><label>Bookable until<input type="time" step={3600} value={rule.end_time} onChange={e=>setRule({...rule,end_time:e.target.value})}/></label><label>Hourly rate<input type="number" min="0" step="50" value={rule.hourly_rate} onChange={e=>setRule({...rule,hourly_rate:e.target.value})}/></label><label>Priority<input type="number" value={rule.priority} onChange={e=>setRule({...rule,priority:e.target.value})}/></label></div><div className="weekdayPicker"><span>Bookable weekdays</span>{weekdays.map((d,i)=><button type="button" className={rule.weekdays.includes(i)?'on':''} onClick={()=>toggleDay(i)} key={d}>{d}</button>)}</div><button className="btn">ADD BOOKABLE HOURS</button></form><div className="provisionList">{pricing.filter(p=>p.is_active).map(p=><div key={p.id}><b>{p.court_id?(courts.find(c=>c.id===p.court_id)?.name||'Court'):'All courts'} · {p.start_time}–{p.end_time}</b><span>{p.currency} {Number(p.hourly_rate).toLocaleString()} · {p.weekdays.length?p.weekdays.map(i=>weekdays[i]).join(', '):'All days'}</span><button onClick={()=>removeRule(p.id)}>DISABLE</button></div>)}{!pricing.some(p=>p.is_active)&&<em>No bookable hours configured.</em>}</div></article>
 <article className="card provisionStep"><span className="stepNo">3</span><h2>Assign venue staff</h2><p>Assignments are reversible without deleting staff accounts.</p><form className="stackForm" onSubmit={assignStaff}><label>Staff<select value={assignment.user_id} onChange={e=>setAssignment({...assignment,user_id:e.target.value})}><option value="">Select manager/operator</option>{staff.filter(s=>s.role==='venue_manager'||s.role==='venue_operator').map(s=><option key={s.id} value={s.id}>{s.full_name} · {s.role.replace('venue_','')}</option>)}</select></label><label>Venue role<select value={assignment.role} onChange={e=>setAssignment({...assignment,role:e.target.value})}><option value="manager">Manager</option><option value="operator">Operator</option></select></label><button className="btn">ASSIGN TO VENUE</button></form><div className="provisionList">{venueAssignments.map(a=><div key={a.id}><b>{a.user_name}</b><span>{a.user_email} · {a.role.toUpperCase()}</span><button onClick={()=>removeAssignment(a.id)}>REMOVE</button></div>)}{!venueAssignments.length&&<em>No venue staff assigned.</em>}</div></article></section></div>}
