'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
type Venue={id:string;name:string;city:string;is_active:boolean;opening_time:string;closing_time:string};
const API=process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:8000/api/v1';
export default function ProvisioningDirectory(){
 const[token,setToken]=useState(''),[venues,setVenues]=useState<Venue[]>([]),[counts,setCounts]=useState<Record<string,number>>({}),[query,setQuery]=useState(''),[showCreate,setShowCreate]=useState(false),[error,setError]=useState('');
 const[form,setForm]=useState({name:'',city:'',address:'',latitude:'31.5204',longitude:'74.3587',opening_time:'06:00',closing_time:'23:00'});
 async function api<T=unknown>(path:string,options:RequestInit={}):Promise<T>{const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},cache:'no-store'});let b:any=null;try{b=await r.json()}catch{}if(!r.ok)throw new Error(typeof b?.detail==='string'?b.detail:`Request failed (${r.status})`);return b as T}
 async function load(){const v=await api<Venue[]>('/admin/venues');setVenues(v);const pairs=await Promise.all(v.map(async x=>{try{return[x.id,(await api<any[]>(`/admin/venues/${x.id}/courts`)).length] as const}catch{return[x.id,0] as const}}));setCounts(Object.fromEntries(pairs))}
 useEffect(()=>{const t=localStorage.getItem('sbp_padel_hq_token')||'';if(!t){location.href='/hq';return}setToken(t)},[]);useEffect(()=>{if(token)load().catch(e=>setError(e.message))},[token]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return !q?venues:venues.filter(v=>`${v.name} ${v.city}`.toLowerCase().includes(q))},[venues,query]);
 async function createVenue(e:FormEvent){e.preventDefault();setError('');try{const v:any=await api('/admin/venues',{method:'POST',body:JSON.stringify({...form,latitude:Number(form.latitude),longitude:Number(form.longitude),amenities:[]})});location.href=`/hq/provisioning/manage?venue=${encodeURIComponent(v.id)}`}catch(e){setError(e instanceof Error?e.message:'Unable to create venue')}}
 return <div className="hqProvision"><header className="top"><div><h1>Venue Directory</h1><p>Select a venue to manage it, or create a new SBP Padel facility.</p></div><div className="toolbar"><a className="btn" href="/hq">BACK TO HQ</a><button className="btn" onClick={()=>setShowCreate(v=>!v)}>{showCreate?'CLOSE FORM':'CREATE NEW VENUE'}</button></div></header>{error&&<div className="error errorBar">{error}<button onClick={()=>setError('')}>×</button></div>}
 {showCreate&&<section className="card hqForm"><div><h2>Create new venue</h2><p>Create the facility first, then add courts, bookable hours/pricing and venue staff.</p></div><form onSubmit={createVenue}><input required placeholder="Venue name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required placeholder="City" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/><input required className="wide" placeholder="Address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><input required placeholder="Latitude" value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})}/><input required placeholder="Longitude" value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})}/><label>Opening<input type="time" value={form.opening_time} onChange={e=>setForm({...form,opening_time:e.target.value})}/></label><label>Closing<input type="time" value={form.closing_time} onChange={e=>setForm({...form,closing_time:e.target.value})}/></label><button className="btn">CREATE & MANAGE VENUE</button></form></section>}
 <section className="card" style={{marginTop:18}}><div className="sectionHead"><div><h2>All venues</h2><p>{venues.length} configured facilities across Punjab</p></div><input style={{minWidth:280}} placeholder="Search venue or city" value={query} onChange={e=>setQuery(e.target.value)}/></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12,marginTop:16}}>{filtered.map(v=><a key={v.id} href={`/hq/provisioning/manage?venue=${encodeURIComponent(v.id)}`} className="card" style={{textDecoration:'none',color:'inherit',padding:18,display:'block'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start'}}><div><small style={{color:'var(--brand)',fontWeight:900}}>{v.city.toUpperCase()}</small><h3 style={{margin:'6px 0'}}>{v.name}</h3><p style={{margin:0,color:'var(--muted)',fontSize:11}}>{v.opening_time}–{v.closing_time} · {counts[v.id]??0} court{(counts[v.id]??0)===1?'':'s'}</p></div><span className={`status ${v.is_active?'':'inactiveState'}`}>{v.is_active?'ACTIVE':'INACTIVE'}</span></div><div style={{marginTop:16,color:'var(--brand)',fontWeight:900,fontSize:11}}>MANAGE VENUE →</div></a>)}{!filtered.length&&<div className="playersEmpty">No venues match your search.</div>}</div></section></div>
}
