'use client';

import { useEffect, useMemo, useState } from 'react';

const API=process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:8000/api/v1';
type Summary={from_date:string;to_date:string;provider:string;currency:string;payment_count:number;paid_amount:string;refund_count:number;refunded_amount:string;net_amount:string;pending_refunds:number};
type Batch={id:string;from_date:string;to_date:string;provider:string;currency:string;paid_amount:string;refunded_amount:string;net_amount:string;payment_count:number;refund_count:number;generated_at:string};
const iso=(d:Date)=>d.toISOString().slice(0,10); const monthStart=()=>{const d=new Date();return iso(new Date(d.getFullYear(),d.getMonth(),1))};

export default function FinancePage(){
 const [token,setToken]=useState('');const [fromDate,setFromDate]=useState(monthStart);const [toDate,setToDate]=useState(()=>iso(new Date()));const [summary,setSummary]=useState<Summary|null>(null);const [batches,setBatches]=useState<Batch[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 const auth=useMemo(()=>({Authorization:`Bearer ${token}`}),[token]);
 async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...auth},cache:'no-store'});let b:any=null;try{b=await r.json()}catch{}if(r.status===401||r.status===403){localStorage.removeItem('sbp_padel_hq_token');location.href='/hq';throw new Error('HQ session expired')}if(!r.ok)throw new Error(b?.detail||'Request failed');return b}
 async function load(){if(fromDate>toDate){setError('From date cannot be after To date.');return}setError('');setLoading(true);try{const[s,b]=await Promise.all([api(`/admin/finance/summary?from_date=${fromDate}&to_date=${toDate}`),api('/admin/finance/reconciliation-batches')]);setSummary(s);setBatches(b)}catch(e){setError(e instanceof Error?e.message:'Unable to load finance data')}finally{setLoading(false)}}
 async function generate(){if(fromDate>toDate){setError('From date cannot be after To date.');return}setError('');setLoading(true);try{await api(`/admin/finance/reconciliation-batches?from_date=${fromDate}&to_date=${toDate}`,{method:'POST'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to generate reconciliation')}finally{setLoading(false)}}
 useEffect(()=>{const t=localStorage.getItem('sbp_padel_hq_token')||'';if(!t){location.href='/hq';return}setToken(t)},[]);useEffect(()=>{if(token)load()},[token]);
 return <main className="main"><header className="top"><div><h1>Finance & Reconciliation</h1><p>Payment settlement, refunds and net collections across SBP Padel.</p></div><a className="btn" href="/hq">BACK TO HQ</a></header>{error&&<div className="error">{error}</div>}<section className="card bookingFilters"><input aria-label="From date" type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/><input aria-label="To date" type="date" value={toDate} onChange={e=>setToDate(e.target.value)}/><button className="btn" disabled={loading} onClick={load}>{loading?'LOADING…':'REFRESH'}</button><button className="btn" disabled={loading} onClick={generate}>GENERATE RECONCILIATION</button></section>{summary&&<><section className="grid section"><div className="card metric"><b>{summary.currency} {summary.paid_amount}</b><span>Paid amount · {summary.payment_count} payments</span></div><div className="card metric"><b>{summary.currency} {summary.refunded_amount}</b><span>Completed refunds · {summary.refund_count}</span></div><div className="card metric"><b>{summary.currency} {summary.net_amount}</b><span>Net collections</span></div><div className="card metric"><b>{summary.pending_refunds}</b><span>Pending refunds</span></div></section><p style={{color:'var(--muted)',fontSize:11}}>Period: {summary.from_date} → {summary.to_date} · Provider: {summary.provider}</p></>}<section className="section"><div className="sectionHead"><h2>Reconciliation batches</h2></div><div className="table"><table><thead><tr><th>PERIOD</th><th>PROVIDER</th><th>PAID</th><th>REFUNDED</th><th>NET</th><th>GENERATED</th></tr></thead><tbody>{batches.map(b=><tr key={b.id}><td>{b.from_date} → {b.to_date}</td><td>{b.provider}</td><td>{b.currency} {b.paid_amount}</td><td>{b.currency} {b.refunded_amount}</td><td><b>{b.currency} {b.net_amount}</b></td><td>{new Date(b.generated_at).toLocaleString()}</td></tr>)}{!batches.length&&<tr><td colSpan={6}>No reconciliation batches generated yet.</td></tr>}</tbody></table></div></section></main>
}
