'use client';

import { useEffect, useMemo, useState } from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:8000/api/v1';
type Summary={from_date:string;to_date:string;provider:string;currency:string;payment_count:number;paid_amount:string;refund_count:number;refunded_amount:string;net_amount:string;pending_refunds:number};
type Batch={id:string;from_date:string;to_date:string;provider:string;currency:string;paid_amount:string;refunded_amount:string;net_amount:string;payment_count:number;refund_count:number;generated_at:string};
type ServiceFee={service_fee:number;currency:string};
const localDate=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const monthStart=()=>{const d=new Date();return localDate(new Date(d.getFullYear(),d.getMonth(),1))};const money=(c:string,v:string|number)=>`${c} ${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:0})}`;
export default function FinancePage(){
 const [token,setToken]=useState('');const [fromDate,setFromDate]=useState(monthStart);const [toDate,setToDate]=useState(()=>localDate(new Date()));const [summary,setSummary]=useState<Summary|null>(null);const [batches,setBatches]=useState<Batch[]>([]);const [serviceFee,setServiceFee]=useState('100');const [savedServiceFee,setSavedServiceFee]=useState<number|null>(null);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);const auth=useMemo(()=>({Authorization:`Bearer ${token}`}),[token]);
 async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...auth},cache:'no-store'});let b:any=null;try{b=await r.json()}catch{}if(r.status===401||r.status===403){localStorage.removeItem('sbp_padel_hq_token');location.href='/hq';throw new Error('HQ session expired')}if(!r.ok)throw new Error(b?.detail||'Request failed');return b}
 async function load(){if(fromDate>toDate){setError('From date cannot be after To date.');return}setError('');setLoading(true);try{const[s,b,f]=await Promise.all([api(`/admin/finance/summary?from_date=${fromDate}&to_date=${toDate}`),api('/admin/finance/reconciliation-batches'),api('/admin/platform-settings/service-fee')]);setSummary(s);setBatches(b);setServiceFee(String((f as ServiceFee).service_fee));setSavedServiceFee((f as ServiceFee).service_fee)}catch(e){setError(e instanceof Error?e.message:'Unable to load finance data')}finally{setLoading(false)}}
 async function generate(){if(fromDate>toDate){setError('From date cannot be after To date.');return}setError('');setLoading(true);try{await api(`/admin/finance/reconciliation-batches?from_date=${fromDate}&to_date=${toDate}`,{method:'POST'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to generate reconciliation')}finally{setLoading(false)}}
 async function saveServiceFee(){const amount=Number(serviceFee);if(!Number.isInteger(amount)||amount<0||amount>100000){setError('Service fee must be a whole PKR amount between 0 and 100,000.');return}setError('');setNotice('');try{const row=await api('/admin/platform-settings/service-fee',{method:'PATCH',body:JSON.stringify({service_fee:amount})}) as ServiceFee;setSavedServiceFee(row.service_fee);setServiceFee(String(row.service_fee));setNotice(`Checkout service fee updated to ${money(row.currency,row.service_fee)}. New quotes and bookings use this amount.`)}catch(e){setError(e instanceof Error?e.message:'Unable to update service fee')}}
 useEffect(()=>{const t=localStorage.getItem('sbp_padel_hq_token')||'';if(!t){location.href='/hq';return}setToken(t)},[]);useEffect(()=>{if(token)load()},[token]);
 return <main className="main hqStandalone"><header className="top"><div><h1>Finance & Reconciliation</h1><p>Payment settlement, refunds, checkout fee and net collections across SBP Padel.</p></div><div className="pill">CENTRAL FINANCE</div></header>{error&&<div className="error">{error}</div>}{notice&&<div className="noticeBar">{notice}<button onClick={()=>setNotice('')}>×</button></div>}<section className="card hqForm"><div><h2>Checkout Service Fee</h2><p>HQ controls the service fee added to every new booking quote. Existing bookings keep the fee captured when they were created.</p></div><form onSubmit={e=>{e.preventDefault();void saveServiceFee()}}><label>Service fee (PKR)<input aria-label="Service fee" type="number" min="0" max="100000" step="1" value={serviceFee} onChange={e=>setServiceFee(e.target.value)}/></label><button className="btn" disabled={savedServiceFee!==null&&Number(serviceFee)===savedServiceFee}>SAVE SERVICE FEE</button></form></section><section className="card bookingFilters"><input aria-label="From date" type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/><input aria-label="To date" type="date" value={toDate} onChange={e=>setToDate(e.target.value)}/><button className="btn" disabled={loading} onClick={load}>{loading?'LOADING…':'REFRESH'}</button><button className="btn" disabled={loading} onClick={generate}>GENERATE RECONCILIATION</button></section>{summary&&<><section className="grid section"><div className="card metric"><b>{money(summary.currency,summary.paid_amount)}</b><span>Paid amount · {summary.payment_count} payments</span></div><div className="card metric"><b>{money(summary.currency,summary.refunded_amount)}</b><span>Completed refunds · {summary.refund_count}</span></div><div className="card metric"><b>{money(summary.currency,summary.net_amount)}</b><span>Net collections</span></div><div className="card metric"><b>{summary.pending_refunds}</b><span>Pending refunds</span></div></section><p className="hqPeriod">Period: {summary.from_date} → {summary.to_date} · Provider: {summary.provider}</p></>}<section className="section"><div className="sectionHead"><div><h2>Reconciliation batches</h2><p className="sectionNote">Immutable settlement snapshots generated for selected periods.</p></div></div><div className="table"><table><thead><tr><th>PERIOD</th><th>PROVIDER</th><th>PAID</th><th>REFUNDED</th><th>NET</th><th>GENERATED</th></tr></thead><tbody>{batches.map(b=><tr key={b.id}><td>{b.from_date} → {b.to_date}</td><td>{b.provider}</td><td>{money(b.currency,b.paid_amount)}</td><td>{money(b.currency,b.refunded_amount)}</td><td><b>{money(b.currency,b.net_amount)}</b></td><td>{new Date(b.generated_at).toLocaleString()}</td></tr>)}{!batches.length&&<tr><td colSpan={6}>No reconciliation batches generated yet.</td></tr>}</tbody></table></div></section></main>
}
