'use client';

import { FormEvent,useEffect,useMemo,useState } from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:8000/api/v1';
type Dashboard={venues:number;courts:number;players:number;confirmed_bookings:number;paid_revenue:string;pending_refunds:number;currency:string};type Venue={id:string;name:string;city:string};type Booking={id:string;booking_code:string;venue_id:string;date:string;status:string;total:string;currency:string};type Staff={id:string;full_name:string;email:string;role:string;is_active:boolean};type Policy={id:string;version:string;title:string;effective_from:string;is_active:boolean};type Refund={id:string;booking_id:string;amount:string;currency:string;status:string;reason:string|null};type Tab='overview'|'bookings'|'staff'|'policies'|'refunds';
export default function HQPage(){
 const[token,setToken]=useState(''),[email,setEmail]=useState('admin@sbppadel.local'),[password,setPassword]=useState(''),[tab,setTab]=useState<Tab>('overview'),[error,setError]=useState(''),[loading,setLoading]=useState(false);const[dash,setDash]=useState<Dashboard|null>(null),[venues,setVenues]=useState<Venue[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[staff,setStaff]=useState<Staff[]>([]),[policies,setPolicies]=useState<Policy[]>([]),[refunds,setRefunds]=useState<Refund[]>([]);const[bookingVenue,setBookingVenue]=useState(''),[bookingStatus,setBookingStatus]=useState(''),[bookingQuery,setBookingQuery]=useState('');const[newStaff,setNewStaff]=useState({full_name:'',email:'',password:'',role:'venue_manager'});const[policy,setPolicy]=useState({version:'',title:'SBP Padel Booking, Cancellation & Refund Policy',body:''});const auth=useMemo(()=>({Authorization:`Bearer ${token}`}),[token]);
 async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?auth:{}),...(options.headers||{})},cache:'no-store'});let b:any=null;try{b=await r.json()}catch{}if((r.status===401||r.status===403)&&token){localStorage.removeItem('sbp_padel_hq_token');setToken('')}if(!r.ok)throw new Error(b?.detail||'Request failed');return b}
 async function login(e:FormEvent){e.preventDefault();setError('');try{const data=await api('/auth/login',{method:'POST',body:JSON.stringify({identifier:email,password})});const me=await fetch(`${API}/auth/me`,{headers:{Authorization:`Bearer ${data.access_token}`}}).then(r=>r.json());if(me.role!=='admin')throw new Error('Central administrator access is required');localStorage.setItem('sbp_padel_hq_token',data.access_token);setToken(data.access_token)}catch(e){setError(e instanceof Error?e.message:'Login failed')}}
 async function load(){setLoading(true);setError('');try{const[d,v,b,s,p,r]=await Promise.all([api('/admin/dashboard'),api('/admin/venues'),api('/admin/bookings'),api('/admin/staff'),api('/admin/policies'),api('/admin/refunds')]);setDash(d);setVenues(v);setBookings(b);setStaff(s);setPolicies(p);setRefunds(r)}catch(e){setError(e instanceof Error?e.message:'Unable to load HQ')}finally{setLoading(false)}}
 async function searchBookings(){const q=new URLSearchParams();if(bookingVenue)q.set('venue_id',bookingVenue);if(bookingStatus)q.set('status',bookingStatus);if(bookingQuery)q.set('q',bookingQuery);try{setBookings(await api(`/admin/bookings?${q}`))}catch(e){setError(e instanceof Error?e.message:'Unable to search bookings')}}
 async function createStaff(e:FormEvent){e.preventDefault();try{await api('/admin/staff',{method:'POST',body:JSON.stringify(newStaff)});setNewStaff({full_name:'',email:'',password:'',role:'venue_manager'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create staff')}}
 async function publishPolicy(e:FormEvent){e.preventDefault();try{await api('/admin/policies/publish',{method:'POST',body:JSON.stringify(policy)});setPolicy({version:'',title:'SBP Padel Booking, Cancellation & Refund Policy',body:''});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to publish policy')}}
 async function advanceRefund(id:string,status:string){try{await api(`/admin/refunds/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update refund')}}
 useEffect(()=>{const t=localStorage.getItem('sbp_padel_hq_token')||'';if(t)setToken(t)},[]);useEffect(()=>{if(token)load()},[token]);
 if(!token)return <main className="login"><form className="loginCard" onSubmit={login}><div className="brand"><small>SPORTS BOARD PUNJAB</small>SBP Padel HQ</div><h1>Central administration</h1><p>Province-wide venue, finance, booking and policy control.</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button className="btn">SIGN IN</button>{error&&<div className="error">{error}</div>}</form></main>;
 const tabs:Tab[]=['overview','bookings','staff','policies','refunds'];return <div className="shell"><aside className="sidebar"><div className="brand"><small>SPORTS BOARD PUNJAB</small>SBP Padel HQ</div><div className="nav">{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div><div className="sidebarRoutes"><a className="sidebarRouteLink" href="/hq/provisioning">Venue Directory</a><a className="sidebarRouteLink" href="/hq/reports">Reports</a><a className="sidebarRouteLink" href="/hq/finance">Finance</a><a className="sidebarRouteLink" href="/hq/audit">Audit Log</a></div></aside><main className="main"><header className="top"><div><h1>{tab==='overview'?'Central Dashboard':tab[0].toUpperCase()+tab.slice(1)}</h1><p>{tab==='overview'?'Province-wide SBP Padel administration.':'Central cross-venue administration.'}</p></div><div className="pill">HEADQUARTERS ADMIN</div></header>{error&&<div className="error">{error}</div>}{loading&&<p style={{color:'var(--muted)'}}>Refreshing HQ data…</p>}
 {tab==='overview'&&dash&&<><section className="grid"><div className="card metric"><b>{dash.venues}</b><span>Venues</span></div><div className="card metric"><b>{dash.courts}</b><span>Courts</span></div><div className="card metric"><b>{dash.players}</b><span>Players</span></div><div className="card metric"><b>{dash.confirmed_bookings}</b><span>Confirmed bookings</span></div></section><section className="grid two"><div className="card metric"><b>{dash.currency} {dash.paid_revenue}</b><span>Paid revenue</span></div><div className="card metric"><b>{dash.pending_refunds}</b><span>Pending refunds</span></div></section><section className="grid section"><a className="card hqShortcut" href="/hq/provisioning"><h2>Venue Directory</h2><p>Provision facilities, courts, bookable hours, pricing and venue assignments.</p></a><a className="card hqShortcut" href="/hq/reports"><h2>Venue Performance</h2><p>Compare bookings, booked hours and paid collections by facility.</p></a><a className="card hqShortcut" href="/hq/finance"><h2>Finance</h2><p>Settlement summaries, refunds and reconciliation batches.</p></a><a className="card hqShortcut" href="/hq/audit"><h2>Audit Log</h2><p>Review administrative and venue-operation changes.</p></a></section></>}
 {tab==='bookings'&&<><section className="card bookingFilters"><select value={bookingVenue} onChange={e=>setBookingVenue(e.target.value)}><option value="">All venues</option>{venues.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><select value={bookingStatus} onChange={e=>setBookingStatus(e.target.value)}><option value="">All statuses</option>{['pending_payment','confirmed','completed','cancelled','expired','payment_failed','venue_cancelled','rescheduled'].map(s=><option key={s}>{s}</option>)}</select><input placeholder="Booking code" value={bookingQuery} onChange={e=>setBookingQuery(e.target.value)}/><button className="btn" onClick={searchBookings}>SEARCH</button></section><section className="section table"><table><thead><tr><th>BOOKING</th><th>VENUE</th><th>DATE</th><th>STATUS</th><th>AMOUNT</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id}><td><b>{b.booking_code}</b></td><td>{venues.find(v=>v.id===b.venue_id)?.name||'Venue'}</td><td>{b.date}</td><td><span className="status">{b.status.toUpperCase()}</span></td><td>{b.currency} {b.total}</td></tr>)}</tbody></table></section></>}
 {tab==='staff'&&<><section className="card hqForm"><div><h2>Create staff account</h2><p>Create central admins, venue managers or operators. Venue assignment is managed inside Venue Directory.</p></div><form onSubmit={createStaff}><input required placeholder="Full name" value={newStaff.full_name} onChange={e=>setNewStaff({...newStaff,full_name:e.target.value})}/><input required type="email" placeholder="Email" value={newStaff.email} onChange={e=>setNewStaff({...newStaff,email:e.target.value})}/><input required type="password" minLength={8} placeholder="Temporary password" value={newStaff.password} onChange={e=>setNewStaff({...newStaff,password:e.target.value})}/><select value={newStaff.role} onChange={e=>setNewStaff({...newStaff,role:e.target.value})}><option value="venue_manager">Venue manager</option><option value="venue_operator">Venue operator</option><option value="admin">Central admin</option></select><button className="btn">CREATE STAFF</button></form></section><section className="section table"><table><thead><tr><th>STAFF</th><th>EMAIL</th><th>ROLE</th><th>STATUS</th></tr></thead><tbody>{staff.map(s=><tr key={s.id}><td><b>{s.full_name}</b></td><td>{s.email}</td><td>{s.role.replaceAll('_',' ')}</td><td><span className="status">{s.is_active?'ACTIVE':'INACTIVE'}</span></td></tr>)}</tbody></table></section></>}
 {tab==='policies'&&<><section className="card hqForm"><div><h2>Publish policy version</h2><p>Publishing a new version makes it the active booking/cancellation policy.</p></div><form onSubmit={publishPolicy}><input required placeholder="Version" value={policy.version} onChange={e=>setPolicy({...policy,version:e.target.value})}/><input required className="wide" placeholder="Title" value={policy.title} onChange={e=>setPolicy({...policy,title:e.target.value})}/><textarea required className="wide" placeholder="Policy body" value={policy.body} onChange={e=>setPolicy({...policy,body:e.target.value})}/><button className="btn">PUBLISH POLICY</button></form></section><section className="section table"><table><thead><tr><th>VERSION</th><th>TITLE</th><th>EFFECTIVE</th><th>STATUS</th></tr></thead><tbody>{policies.map(p=><tr key={p.id}><td><b>{p.version}</b></td><td>{p.title}</td><td>{new Date(p.effective_from).toLocaleString()}</td><td><span className="status">{p.is_active?'ACTIVE':'ARCHIVED'}</span></td></tr>)}</tbody></table></section></>}
 {tab==='refunds'&&<section className="section table"><table><thead><tr><th>BOOKING</th><th>AMOUNT</th><th>STATUS</th><th>REASON</th><th>ACTION</th></tr></thead><tbody>{refunds.map(r=><tr key={r.id}><td>{r.booking_id.slice(0,8)}</td><td>{r.currency} {r.amount}</td><td><span className="status">{r.status.toUpperCase()}</span></td><td>{r.reason||'—'}</td><td>{r.status==='requested'?<button className="btn" onClick={()=>advanceRefund(r.id,'processing')}>PROCESS</button>:r.status==='processing'?<button className="btn" onClick={()=>advanceRefund(r.id,'completed')}>COMPLETE</button>:'—'}</td></tr>)}{!refunds.length&&<tr><td colSpan={5}>No refund requests.</td></tr>}</tbody></table></section>}
 </main></div>
}
