'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';

type Venue={id:string;name:string;city:string;is_active:boolean;opening_time:string;closing_time:string};
type Staff={id:string;full_name:string;email:string;role:string;is_active:boolean};
type Assignment={id:string;user_id:string;user_name:string;user_email:string;venue_id:string;venue_name:string;role:string};
type Policy={id:string;version:string;title:string;effective_from:string;is_active:boolean};
type Refund={id:string;booking_id:string;payment_id:string;amount:string;currency:string;status:string;reason:string|null};
type Dashboard={venues:number;courts:number;players:number;confirmed_bookings:number;paid_revenue:string;pending_refunds:number;currency:string};

const API=process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:8000/api/v1';

export default function HQPage(){
  const [token,setToken]=useState('');
  const [email,setEmail]=useState('admin@sbppadel.local');
  const [password,setPassword]=useState('PadelAdmin2026!');
  const [error,setError]=useState('');
  const [tab,setTab]=useState<'dashboard'|'venues'|'staff'|'policies'|'refunds'>('dashboard');
  const [dash,setDash]=useState<Dashboard|null>(null);
  const [venues,setVenues]=useState<Venue[]>([]);
  const [staff,setStaff]=useState<Staff[]>([]);
  const [assignments,setAssignments]=useState<Assignment[]>([]);
  const [policies,setPolicies]=useState<Policy[]>([]);
  const [refunds,setRefunds]=useState<Refund[]>([]);
  const [newVenue,setNewVenue]=useState({name:'',city:'',address:'',latitude:'',longitude:'',opening_time:'06:00',closing_time:'23:00'});
  const [newStaff,setNewStaff]=useState({full_name:'',email:'',password:'',role:'venue_manager'});
  const [assign,setAssign]=useState({user_id:'',venue_id:'',role:'manager'});
  const [policy,setPolicy]=useState({version:'',title:'SBP Padel Booking, Cancellation & Refund Policy',body:''});
  const auth=useMemo(()=>({Authorization:`Bearer ${token}`}),[token]);

  async function api(path:string,options:RequestInit={}){
    const res=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?auth:{}),...(options.headers||{})}});
    if(!res.ok){let detail='Request failed';try{detail=(await res.json()).detail||detail}catch{};throw new Error(detail)}
    return res.json();
  }

  async function login(e:FormEvent){e.preventDefault();setError('');try{const data=await api('/auth/login',{method:'POST',body:JSON.stringify({identifier:email,password})});const me=await fetch(`${API}/auth/me`,{headers:{Authorization:`Bearer ${data.access_token}`}}).then(r=>r.json());if(me.role!=='admin')throw new Error('Central administrator access is required');setToken(data.access_token);localStorage.setItem('sbp_padel_hq_token',data.access_token)}catch(err){setError(err instanceof Error?err.message:'Login failed')}}
  async function loadAll(){const [d,v,s,a,p,r]=await Promise.all([api('/admin/dashboard'),api('/admin/venues'),api('/admin/staff'),api('/admin/staff-assignments'),api('/admin/policies'),api('/admin/refunds')]);setDash(d);setVenues(v);setStaff(s);setAssignments(a);setPolicies(p);setRefunds(r)}
  useEffect(()=>{const t=localStorage.getItem('sbp_padel_hq_token');if(t)setToken(t)},[]);
  useEffect(()=>{if(token)loadAll().catch(e=>{setError(e.message);setToken('')})},[token]);

  async function createVenue(e:FormEvent){e.preventDefault();try{await api('/admin/venues',{method:'POST',body:JSON.stringify({...newVenue,latitude:Number(newVenue.latitude),longitude:Number(newVenue.longitude),amenities:[]})});setNewVenue({name:'',city:'',address:'',latitude:'',longitude:'',opening_time:'06:00',closing_time:'23:00'});await loadAll()}catch(err){setError(err instanceof Error?err.message:'Unable to create venue')}}
  async function createStaff(e:FormEvent){e.preventDefault();try{await api('/admin/staff',{method:'POST',body:JSON.stringify(newStaff)});setNewStaff({full_name:'',email:'',password:'',role:'venue_manager'});await loadAll()}catch(err){setError(err instanceof Error?err.message:'Unable to create staff')}}
  async function assignStaff(e:FormEvent){e.preventDefault();try{await api('/admin/staff-assignments',{method:'POST',body:JSON.stringify(assign)});await loadAll()}catch(err){setError(err instanceof Error?err.message:'Unable to assign staff')}}
  async function publishPolicy(e:FormEvent){e.preventDefault();try{await api('/admin/policies/publish',{method:'POST',body:JSON.stringify(policy)});setPolicy({version:'',title:'SBP Padel Booking, Cancellation & Refund Policy',body:''});await loadAll()}catch(err){setError(err instanceof Error?err.message:'Unable to publish policy')}}
  async function advanceRefund(id:string,status:string){try{await api(`/admin/refunds/${id}`,{method:'PATCH',body:JSON.stringify({status})});await loadAll()}catch(err){setError(err instanceof Error?err.message:'Unable to update refund')}}

  if(!token)return <main className="login"><form className="loginCard" onSubmit={login}><div className="brand"><small>SPORTS BOARD PUNJAB</small>SBP Padel HQ</div><h1>Central administration</h1><p>Province-wide venue, finance and policy control.</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button className="btn">SIGN IN</button>{error&&<div className="error">{error}</div>}</form></main>;

  return <div className="shell"><aside className="sidebar"><div className="brand"><small>SPORTS BOARD PUNJAB</small>SBP Padel HQ</div><div className="nav">{(['dashboard','venues','staff','policies','refunds'] as const).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x==='dashboard'?'Overview':x[0].toUpperCase()+x.slice(1)}</button>)}</div></aside><main className="main"><header className="top"><div><h1>{tab==='dashboard'?'Central Dashboard':tab[0].toUpperCase()+tab.slice(1)}</h1><p>Province-wide SBP Padel administration.</p></div><div className="pill">HEADQUARTERS ADMIN</div></header>{error&&<div className="error">{error}</div>}
  {tab==='dashboard'&&dash&&<><section className="grid"><div className="card metric"><b>{dash.venues}</b><span>Venues</span></div><div className="card metric"><b>{dash.courts}</b><span>Courts</span></div><div className="card metric"><b>{dash.players}</b><span>Players</span></div><div className="card metric"><b>{dash.confirmed_bookings}</b><span>Confirmed bookings</span></div></section><section className="grid two"><div className="card metric"><b>{dash.currency} {dash.paid_revenue}</b><span>Paid revenue</span></div><div className="card metric"><b>{dash.pending_refunds}</b><span>Pending refunds</span></div></section></>}
  {tab==='venues'&&<><section className="card hqForm"><div><h2>Add venue</h2><p>Create future SBP Padel facilities anywhere in Punjab.</p></div><form onSubmit={createVenue}><input placeholder="Venue name" value={newVenue.name} onChange={e=>setNewVenue({...newVenue,name:e.target.value})}/><input placeholder="City" value={newVenue.city} onChange={e=>setNewVenue({...newVenue,city:e.target.value})}/><input className="wide" placeholder="Address" value={newVenue.address} onChange={e=>setNewVenue({...newVenue,address:e.target.value})}/><input placeholder="Latitude" value={newVenue.latitude} onChange={e=>setNewVenue({...newVenue,latitude:e.target.value})}/><input placeholder="Longitude" value={newVenue.longitude} onChange={e=>setNewVenue({...newVenue,longitude:e.target.value})}/><button className="btn">ADD VENUE</button></form></section><section className="section"><div className="sectionHead"><h2>All venues</h2></div><div className="table"><table><thead><tr><th>VENUE</th><th>CITY</th><th>HOURS</th><th>STATUS</th></tr></thead><tbody>{venues.map(v=><tr key={v.id}><td><b>{v.name}</b></td><td>{v.city}</td><td>{v.opening_time}–{v.closing_time}</td><td><span className="status">{v.is_active?'ACTIVE':'INACTIVE'}</span></td></tr>)}</tbody></table></div></section></>}
  {tab==='staff'&&<><section className="card hqForm"><div><h2>Create staff account</h2><p>Central admins, venue managers and front-desk operators.</p></div><form onSubmit={createStaff}><input placeholder="Full name" value={newStaff.full_name} onChange={e=>setNewStaff({...newStaff,full_name:e.target.value})}/><input placeholder="Email" value={newStaff.email} onChange={e=>setNewStaff({...newStaff,email:e.target.value})}/><input placeholder="Temporary password" value={newStaff.password} onChange={e=>setNewStaff({...newStaff,password:e.target.value})}/><select value={newStaff.role} onChange={e=>setNewStaff({...newStaff,role:e.target.value})}><option value="venue_manager">Venue manager</option><option value="venue_operator">Venue operator</option><option value="admin">Central admin</option></select><button className="btn">CREATE</button></form></section><section className="card hqForm section"><div><h2>Assign venue</h2><p>Scope manager/operator access to a specific facility.</p></div><form onSubmit={assignStaff}><select value={assign.user_id} onChange={e=>setAssign({...assign,user_id:e.target.value})}><option value="">Select staff</option>{staff.filter(s=>s.role!=='admin').map(s=><option key={s.id} value={s.id}>{s.full_name} · {s.role}</option>)}</select><select value={assign.venue_id} onChange={e=>setAssign({...assign,venue_id:e.target.value})}><option value="">Select venue</option>{venues.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><select value={assign.role} onChange={e=>setAssign({...assign,role:e.target.value})}><option value="manager">Manager</option><option value="operator">Operator</option></select><button className="btn">ASSIGN</button></form></section><section className="section"><div className="table"><table><thead><tr><th>STAFF</th><th>EMAIL</th><th>VENUE</th><th>ROLE</th></tr></thead><tbody>{assignments.map(a=><tr key={a.id}><td>{a.user_name}</td><td>{a.user_email}</td><td>{a.venue_name}</td><td><span className="status">{a.role.toUpperCase()}</span></td></tr>)}</tbody></table></div></section></>}
  {tab==='policies'&&<><section className="card hqForm"><div><h2>Publish policy</h2><p>Publishing a new version makes it the policy players must accept before payment.</p></div><form onSubmit={publishPolicy}><input placeholder="Version e.g. 2026-01" value={policy.version} onChange={e=>setPolicy({...policy,version:e.target.value})}/><input className="wide" placeholder="Policy title" value={policy.title} onChange={e=>setPolicy({...policy,title:e.target.value})}/><textarea className="wide" placeholder="Full booking, cancellation and refund policy" value={policy.body} onChange={e=>setPolicy({...policy,body:e.target.value})}/><button className="btn">PUBLISH POLICY</button></form></section><section className="section"><div className="table"><table><thead><tr><th>VERSION</th><th>TITLE</th><th>EFFECTIVE</th><th>STATUS</th></tr></thead><tbody>{policies.map(p=><tr key={p.id}><td>{p.version}</td><td>{p.title}</td><td>{new Date(p.effective_from).toLocaleString()}</td><td><span className="status">{p.is_active?'ACTIVE':'ARCHIVED'}</span></td></tr>)}</tbody></table></div></section></>}
  {tab==='refunds'&&<section className="section"><div className="sectionHead"><h2>Refund oversight</h2></div><div className="table"><table><thead><tr><th>REFUND</th><th>AMOUNT</th><th>STATUS</th><th>REASON</th><th>ACTION</th></tr></thead><tbody>{refunds.map(r=><tr key={r.id}><td>{r.id.slice(0,8)}</td><td>{r.currency} {r.amount}</td><td><span className="status">{r.status.toUpperCase()}</span></td><td>{r.reason||'—'}</td><td>{r.status==='requested'?<button className="btn" onClick={()=>advanceRefund(r.id,'processing')}>START</button>:r.status==='processing'?<button className="btn" onClick={()=>advanceRefund(r.id,'completed')}>COMPLETE</button>:'—'}</td></tr>)}</tbody></table></div></section>}
  </main></div>
}
