import { chromium } from 'playwright';

const base = process.env.SBP_PLAYER_URL || 'http://127.0.0.1:5173';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 412, height: 915 } });
const today=new Date(),iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const future=new Date(today);future.setDate(today.getDate()+4);let bookingDate=iso(future),bookingStatus='confirmed',bookingListDelayMs=0,bookingCourtId='court-life',lastReschedulePayload=null;
const venue={id:'venue-life',name:'Nishtar Park Sports Complex',city:'Lahore',address:'National Stadium',latitude:31.5,longitude:74.3,opening_time:'06:00',closing_time:'23:00',timezone:'Asia/Karachi'},court={id:'court-life',name:'Court 01',court_type:'Championship',is_indoor:false},court2={id:'court-life-2',name:'Court 02',court_type:'Training',is_indoor:false};
const booking=()=>({id:'booking-live-1',booking_code:'PDL-LIFECYCLE',venue_id:venue.id,court_id:bookingCourtId,date:bookingDate,total:2200,court_fee:2100,status:bookingStatus,payment_status:'paid'}),detail=()=>({...booking(),slots:[{start_time:'15:00',end_time:'16:00'}]}),payment={id:'payment-live-1',booking_id:'booking-live-1',status:'paid',method:'card',provider_reference:'PAY-LIFECYCLE'},availability=date=>({venue_id:venue.id,date,timezone:venue.timezone,courts:[{court_id:court.id,court_name:court.name,court_type:court.court_type,slots:[{start_time:'13:00',end_time:'14:00',available:true,hourly_rate:2500},{start_time:'15:00',end_time:'16:00',available:true,hourly_rate:2100}]},{court_id:court2.id,court_name:court2.name,court_type:court2.court_type,slots:[{start_time:'16:00',end_time:'17:00',available:true,hourly_rate:2100}]}]});let refundRequested=false;
await page.route('http://127.0.0.1:8000/api/v1/**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname.replace('/api/v1','');let body={};if(path==='/bookings/me'){if(bookingListDelayMs)await new Promise(r=>setTimeout(r,bookingListDelayMs));body=[booking()]}else if(path==='/venues')body=[venue];else if(path===`/venues/${venue.id}`)body={...venue,courts:[court,court2]};else if(path===`/venues/${venue.id}/availability`)body=availability(url.searchParams.get('date'));else if(path===`/bookings/${booking().id}`)body=detail();else if(path===`/bookings/${booking().id}/participants`)body={player_count:1,players:['Lifecycle QA']};else if(path===`/payments/by-booking/${booking().id}`)body=payment;else if(path===`/bookings/${booking().id}/reschedule`&&req.method()==='POST'){const payload=req.postDataJSON();lastReschedulePayload=payload;bookingDate=payload.booking_date;bookingCourtId=payload.court_id||bookingCourtId;bookingStatus='rescheduled';body=detail()}else if(path===`/bookings/${booking().id}/cancel`&&req.method()==='POST'){bookingStatus='cancelled';body={...detail(),refund_required:true}}else if(path===`/payments/${payment.id}/refund`&&req.method()==='POST'){refundRequested=true;body={status:'requested',amount:2200}}else if(path==='/auth/me')body={id:'user-life',full_name:'Lifecycle QA'};else if(path==='/notifications/me')body=[];else if(path==='/payments/me')body=[{...payment,refund:refundRequested?{status:'requested',amount:2200,reason:'Booking cancelled by player'}:null}];await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)})});
await page.addInitScript(()=>{localStorage.setItem('sbpPadelAccessToken','qa-token');localStorage.setItem('sbpPadelUser',JSON.stringify({id:'user-life',full_name:'Lifecycle QA'}))});
const assert=(condition,message)=>{if(!condition)throw new Error(message)};
try{
 await page.goto(`${base}/index.html?open=bookings`,{waitUntil:'networkidle'});await page.waitForFunction(()=>document.getElementById('bookings')?.innerText.includes('PDL-LIFECYCLE'));assert((await page.locator('#bookings').innerText()).includes('PDL-LIFECYCLE'),'Live booking did not appear.');bookingListDelayMs=250;const manageRefresh=page.evaluate(()=>window.SBPRefreshBookings());await page.waitForTimeout(20);await page.locator('#bookings [data-live-manage="booking-live-1"]').click();await page.waitForSelector('#sbpDeepLayer.on');await manageRefresh;bookingListDelayMs=0;assert(await page.locator('#sbpDeepLayer').evaluate(el=>el.classList.contains('on')),'A background bookings refresh cancelled the first Manage Booking navigation.');
 const frame=page.frameLocator('#sbpDeepFrame');await frame.locator('#id').waitFor();await frame.locator('#id').filter({hasText:'PDL-LIFECYCLE'}).waitFor();assert((await frame.locator('#statusPill').innerText())==='CONFIRMED','Booking detail did not hydrate the live status.');assert((await frame.locator('#transactionId').innerText())==='PAY-LIFECYCLE','Booking detail did not hydrate the real payment reference.');
 await frame.locator('#rescheduleBtn').click();await frame.locator('#rescheduleModal.show').waitFor();const quickDates=frame.locator('#rescheduleModal .dates button[data-date]');assert(await quickDates.count()===6,'Reschedule did not offer six quick date choices.');assert(await frame.locator('#rescheduleModal .dates button[data-more-date]').count()===1,'Reschedule did not expose More date selection.');assert(await frame.locator('#rescheduleModal .dates input[type="date"]').count()===1,'Reschedule More control is missing its date picker.');await quickDates.nth(1).click();await frame.locator('#rescheduleModal .rescheduleCourts [data-rs-court]').first().waitFor();assert(await frame.locator('#rescheduleModal .rescheduleCourts [data-rs-court]').count()===2,'Reschedule did not expose all available courts at the venue.');
 const courtFlow=await frame.locator('#rescheduleModal .rescheduleCourts').evaluate(el=>getComputedStyle(el).display);assert(courtFlow==='flex','Reschedule courts are not presented as a one-row button rail.');
 const currentCourt=frame.locator('#rescheduleModal [data-rs-court="court-life"]');await currentCourt.click();const expensive=frame.locator('#rescheduleModal .slotRow[data-start="13:00"]');await expensive.click();assert(await frame.locator('#confirmReschedule').isDisabled(),'Price-mismatched reschedule remained actionable.');assert((await frame.locator('#confirmReschedule').innerText()).includes('PRICE MUST MATCH'),'Price mismatch was not explained on the action button.');assert(await frame.locator('#rescheduleModal .slotRow .slotPick').count()>0,'Reschedule availability did not render booking-style slot cards.');
 const alternateCourt=frame.locator('#rescheduleModal [data-rs-court="court-life-2"]');await alternateCourt.click();const alternateSlot=frame.locator('#rescheduleModal .slotRow[data-start="16:00"]');await alternateSlot.click();assert(!(await frame.locator('#confirmReschedule').isDisabled()),'Same-price alternate court did not become actionable.');await frame.locator('#confirmReschedule').click();await frame.locator('#statusPill').filter({hasText:'RESCHEDULED'}).waitFor();assert(lastReschedulePayload?.court_id==='court-life-2','Player reschedule did not submit the selected replacement court.');assert(bookingCourtId==='court-life-2','Reschedule did not move the booking to the alternate court.');
 await frame.locator('#cancelBtn').click();await frame.locator('#cancelModal.show').waitFor();await frame.locator('#confirmCancel').click();await frame.locator('#cancelModal').waitFor({state:'hidden'});await frame.locator('#statusPill').filter({hasText:'CANCELLED'}).waitFor();await frame.locator('#refundState').waitFor();await frame.locator('#refundState').filter({hasText:'REFUND REQUESTED'}).waitFor();await page.waitForTimeout(1050);assert(await frame.locator('#passBtn').count()===0,'Cancelled booking still exposed View Pass.');assert(await frame.locator('#rescheduleBtn').count()===0,'Cancelled booking still exposed Reschedule.');assert(await frame.locator('#cancelBtn').count()===0,'Cancelled booking still exposed Cancel Booking.');
 await page.evaluate(()=>{localStorage.setItem('sbpPadelSelectedBookingId','booking-live-1');const f=document.getElementById('sbpDeepFrame');f.src='digital-pass.html?booking=booking-live-1'});await page.waitForFunction(()=>document.getElementById('sbpDeepFrame')?.getAttribute('src')?.includes('digital-pass.html'));const passFrame=page.frameLocator('#sbpDeepFrame');await passFrame.locator('.qr').filter({hasText:'PASS INVALID'}).waitFor();assert((await passFrame.locator('.top').innerText()).includes('PASS INVALID'),'Cancelled digital pass still presented itself as valid.');
 await page.evaluate(()=>window.SBPDeepClose(false));await page.waitForTimeout(180);await page.evaluate(()=>window.SBPNavigate('bookings'));await page.waitForFunction(()=>document.getElementById('bookings')?.classList.contains('active'));await page.evaluate(()=>window.SBPRefreshBookings());await page.waitForFunction(()=>document.getElementById('bookings')?.innerText.includes('Cancelled (1)'));console.log('Player booking lifecycle browser QA passed: one-row reschedule date/court rails, booking-style slot cards, cross-court reschedule, cancellation action integrity and invalid-pass behavior are enforced.');
}finally{await browser.close()}
